/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JLabel;
import javax.swing.event.DocumentListener;

/**
 *
 * @author THIS PC
 */
public class HeaderCustom extends javax.swing.JPanel {

    /**
     * Creates new form HeaderCustom
     */
    public HeaderCustom() {
        initComponents();
        setOpaque(false);
    }
    private int shadowSize = 3;   // Độ dày bóng
    private int arc = 10;  
     @Override
    protected void paintComponent(Graphics g) {
        
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int width = getWidth();
        int height = getHeight();

        // Vẽ nhiều lớp mờ dần ra ngoài → tạo hiệu ứng shadow 4 phía
        for (int i = shadowSize; i >= 1; i--) {
            float opacity = (float) i / (shadowSize * 10f); // càng xa càng mờ
            g2.setColor(new Color(0, 0, 0, opacity));
            g2.fillRoundRect(
                    shadowSize - i,
                    shadowSize - i,
                    width - (shadowSize - i) * 2,
                    height - (shadowSize - i) * 2,
                    arc, arc
            );
        }

        // Vẽ phần panel chính
        g2.setColor(getBackground());
        g2.fillRoundRect(shadowSize, shadowSize,
                width - shadowSize * 2, height - shadowSize * 2,
                arc, arc);

        g2.dispose();
        super.paintComponent(g);
    }

    public String getSearchText(){
        return seachBar1.getTextSearch();
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seachBar1 = new iuh.fit.se.group1.ui.component.SeachBar();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(108, 165, 200));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lí dịch vụ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(seachBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(seachBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

      public void handleSeacrh (DocumentListener listener){
        seachBar1.handleSearch(listener);
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private iuh.fit.se.group1.ui.component.SeachBar seachBar1;
    // End of variables declaration//GEN-END:variables
}
