#Updated by application
#Tue Dec 09 09:52:26 GMT+07:00 2025
/price.double.daily=50000
/price.double.firsthour=30000
/price.double.hourly=80000
/price.double.overnight=300000
/price.single.daily=300000
/price.single.firsthour=20000
/price.single.hourly=50000
/price.single.overnight=250000
