#Updated by application
#Mon Dec 08 18:29:00 ICT 2025
/price.double.daily=50000
/price.double.firsthour=30000
/price.double.hourly=100000
/price.double.overnight=500000
/price.single.daily=100000
/price.single.firsthour=99990000
/price.single.hourly=90000
/price.single.overnight=350000
