/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.table;

import iuh.fit.se.group1.util.Constants;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author vietn
 */
public class PanelAction extends javax.swing.JPanel {

    /**
     * Creates new form panelAction
     */
    public PanelAction() {
        initComponents();
        setOpaque(false);  
        btnEdit.setIcon(FontIcon.of(FontAwesomeSolid.PEN, 17, new java.awt.Color(30, 144, 255)));
        btnEdit.setBorder(null);
        btnEdit.setFocusPainted(false);
        btnEdit.setContentAreaFilled(false); 
        btnEdit.setOpaque(false);
        btnEdit.setBackground(new Color(0,0,0,0));

        btnDelete.setIcon(FontIcon.of(FontAwesomeSolid.TRASH, 17, new java.awt.Color(220, 53, 69)));
        btnDelete.setBorder(null);
        btnDelete.setFocusPainted(false);
        btnDelete.setContentAreaFilled(false);
        btnDelete.setOpaque(false);
        btnDelete.setBackground(new Color(0,0,0,0));
    }
    public void initEvent(TableActionEvent event, int row){
        btnEdit.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent ae){
               event.onEdit(row);
           }
        });
        btnDelete.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent ae){
               event.onDelete(row);
           }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdit = new iuh.fit.se.group1.ui.component.custom.ActionButton();
        btnDelete = new iuh.fit.se.group1.ui.component.custom.ActionButton();

        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.ActionButton btnDelete;
    private iuh.fit.se.group1.ui.component.custom.ActionButton btnEdit;
    // End of variables declaration//GEN-END:variables
}
