package iuh.fit.se.group1.network;

import java.io.Serializable;

public enum CommandType implements Serializable {
    AUTH_LOGIN,
    AUTH_LOGOUT,
    AUTH_RESET_PASSWORD,
    AUTH_VALIDATE_MANAGER,
    AUTH_CHANGE_PASSWORD,


    EMPLOYEE_GET_BY_ID,
    EMPLOYEE_GET_BY_ACCOUNT_ID,
    EMPLOYEE_GET_BY_CITIZEN,
    EMPLOYEE_GET_BY_ALL,
    EMPLOYEE_GET_BY_KEYWORDS,
    EMPLOYEE_GET_BY_CITIZEN_ID,
    EMPLOYEE_GET_BY_ROLE_ID,
    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,
    EMPLOYEE_DELETE,

    AMENITY_GET_BY_ID,
    AMENITY_GET_BY_ALL,
    AMENITY_GET_BY_KEYWORDS,
    AMENITY_CREATE,
    AMENITY_UPDATE,
    AMENITY_DELETE,

    ORDER_GET_BY_ID,
    ORDER_GET_ALL,
    ORDER_GET_ALL_WITH_RELATIONSHIP,
    ORDER_GET_UNPAID,
    ORDER_GET_UNPAID_BY_KEYWORD,
    ORDER_SEARCH_BY_KEYWORD,
    ORDER_CREATE,
    ORDER_UPDATE_STATUS_PAID,
    ORDER_UPDATE_DEPOSIT,
    ORDER_DELETE;



}
