package iuh.fit.se.group1.network;

import java.io.Serializable;

public enum CommandType implements Serializable {
    AUTH_LOGIN,
    AUTH_LOGOUT,
    AUTH_RESET_PASSWORD,
    AUTH_VALIDATE_MANAGER,
    AUTH_CHANGE_PASSWORD,


    EMPLOYEE_GET_BY_ID,
    EMPLOYEE_GET_BY_ACCOUNT_ID,
    EMPLOYEE_GET_BY_CITIZEN,
    EMPLOYEE_GET_ALL,
    EMPLOYEE_GET_BY_KEYWORDS,
    EMPLOYEE_GET_BY_CITIZEN_ID,
    EMPLOYEE_GET_BY_ROLE_ID,
    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,
    EMPLOYEE_DELETE,

    AMENITY_GET_BY_ID,
    AMENITY_GET_ALL,
    AMENITY_GET_BY_KEYWORDS,
    AMENITY_CREATE,
    AMENITY_UPDATE,
    AMENITY_DELETE,

    ORDER_GET_BY_ID,
    ORDER_GET_ALL,
    ORDER_GET_ALL_WITH_RELATIONSHIP,
    ORDER_GET_UNPAID,
    ORDER_GET_UNPAID_BY_KEYWORD,
    ORDER_SEARCH_BY_KEYWORD,
    ORDER_CREATE,
    ORDER_UPDATE_STATUS_PAID,
    ORDER_UPDATE_DEPOSIT,
    ORDER_DELETE,
    ORDER_GET_REVENUE_BETWEEN_DATES,
    ORDER_GET_REVENUE_BETWEEN_DATES_BY_ROOM_TYPE,
    ORDER_GET_REVENUE_BETWEEN_DATES_BOOKING_COUNT,
    ORDER_CREATE_RECORD,
    ORDER_UPDATE_TOTAL_PRICE,
    ORDER_MOVE_BOOKING_TO_ORDER,
    ORDER_RE_CALCULATE_TOTAL_PRICE,
    ORDER_UPDATE_ORDER_TYPE,

    ORDER_DETAIL_GET_BY_ID,
    ORDER_DETAIL_DELETE_BY_ID,
    ORDER_DETAIL_CREATE,
    ORDER_DETAIL_FROM_ORDER,
    ORDER_DETAIL_UPDATE_FROM_ORDER,

    BOOKING_GET_PRICE_FROM_BOOKING,

    CUSTOMER_GET_BY_ID,
    CUSTOMER_GET_ALL,
    CUSTOMER_GET_BY_KEYWORDS,
    CUSTOMER_CREATE,
    CUSTOMER_UPDATE,
    CUSTOMER_DELETE,
    CUSTOMER_GET_BY_CITIZEN,

    EMAIL_SEND,


}
