/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.booking2;

import javax.swing.*;

/**
 *
 * @author THIS PC
 */
public class BookingPage extends javax.swing.JPanel {

    private  MainFlow3 mainFlow3;
    private MainFlow2 mainFlow2;

    /**
     * Creates new form BookingPage
     */
    public BookingPage() {
        initComponents();

        mainFlow2 = new MainFlow2();
        mainFlow3 = new MainFlow3();
        header.getLblTile().setText("Đặt phòng khách sạn");
        header.getLblSubTitle().setText("");
        
        mainFlow1.getCbmBookingType().addActionListener(e ->{
            if (mainFlow1.getCbmBookingType().getSelectedIndex()==0) {
                mainFlow1.setVisiableTimeBooking(true);
            }else {
                mainFlow1.setVisiableTimeBooking(false);
            }
        });

        sequenceBooking.setActiveStep(0);
        mainFlow1.getBtnNext().addActionListener(e-> {
            sequenceBooking.setActiveStep(1);
            scrollPaneWin111.setViewportView(mainFlow2);
        });

        mainFlow2.getBtnPrev().addActionListener(e -> {
            sequenceBooking.setActiveStep(0);
            scrollPaneWin111.setViewportView(mainFlow1);
        });

        mainFlow2.getBtnNext().addActionListener(e -> {
            sequenceBooking.setActiveStep(2);
            scrollPaneWin111.setViewportView(mainFlow3);
        });



        mainFlow3.getBtnPrev().addActionListener(e -> {
            sequenceBooking.setActiveStep(1);
            scrollPaneWin111.setViewportView(mainFlow2);
        });

        mainFlow3.getBtnNext().addActionListener(e -> {
            sequenceBooking.setActiveStep(3);
            scrollPaneWin111.setViewportView(new JPanel());
        });

    }

    
       public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrame frame = new JFrame();
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            BookingPage seq = new BookingPage();
            frame.add(seq);
            frame.pack();
            frame.setVisible(true);
            
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new iuh.fit.se.group1.ui.component.HeaderShift();
        sequenceBooking = new iuh.fit.se.group1.ui.component.booking2.SequenceBooking();
        scrollPaneWin111 = new iuh.fit.se.group1.ui.component.scroll.ScrollPaneWin11();
        mainFlow1 = new iuh.fit.se.group1.ui.component.booking2.MainFlow1();

        setBackground(new java.awt.Color(241, 241, 241));
        setForeground(new java.awt.Color(241, 241, 241));

        scrollPaneWin111.setViewportView(mainFlow1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sequenceBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPaneWin111, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sequenceBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.HeaderShift header;
    private iuh.fit.se.group1.ui.component.booking2.MainFlow1 mainFlow1;
    private iuh.fit.se.group1.ui.component.scroll.ScrollPaneWin11 scrollPaneWin111;
    private iuh.fit.se.group1.ui.component.booking2.SequenceBooking sequenceBooking;
    // End of variables declaration//GEN-END:variables
}
