/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.booking2;

import iuh.fit.se.group1.entity.Customer;
import iuh.fit.se.group1.service.CustomerService;
import iuh.fit.se.group1.ui.component.custom.Button;
import iuh.fit.se.group1.ui.component.custom.TextField;
import iuh.fit.se.group1.ui.component.custom.message.CustomDialog;

import javax.swing.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.ResolverStyle;

/**
 * @author THIS PC
 */
public class MainFlow4 extends javax.swing.JPanel {
    public TextField getTxtDob() {
        return txtDob;
    }

    public void setTxtDob(TextField txtDob) {
        this.txtDob = txtDob;
    }

    public Button getBtnNext() {
        return btnNext;
    }

    public void setBtnNext(Button btnNext) {
        this.btnNext = btnNext;
    }

    public Button getBtnPrev() {
        return btnPrev;
    }

    public void setBtnPrev(Button btnPrev) {
        this.btnPrev = btnPrev;
    }

    /**
     * Creates new form MainFlow4
     */
    public MainFlow4() {
        initComponents();
    }

    public boolean validateInput() {

        String citizenIdOrPassport = txtCitizenIdOrPassport.getText().trim();
        String fullName = txtFullName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();

        // Validate CMND/CCCD hoặc Passport
        if (citizenIdOrPassport.isEmpty()) {
            showError("CCCD/Passport không được để trống!", 400, 200);
            return false;
        }

        // CCCD Việt Nam: 12 số hoặc 9 số (CMND cũ)
        String regexCCCD = "^(\\d{12})$";
        // Passport quốc tế: 1 chữ cái + 7 số (phổ biến VN: B1234567)
        String regexPassport = "^[A-Za-z][0-9]{7,8}$";

        if (!citizenIdOrPassport.matches(regexCCCD) &&
                !citizenIdOrPassport.matches(regexPassport)) {
            showError("CCCD/Passport không hợp lệ!", 500, 200);
            return false;
        }

        // Validate tên
        if (fullName.isEmpty()) {
            showError("Họ tên không được để trống!", 500, 200);
            return false;
        }

        // Tên chỉ gồm chữ + khoảng trắng, không số, không ký tự đặc biệt
        if (!fullName.matches("^(\\p{L}{2,})(\\s+\\p{L}{2,})+$")) {
            showError("Tên phải gồm ít nhất 2 từ, mỗi từ từ 2 ký tự trở lên và không chứa số/ký tự đặc biệt!", 700, 200);
            return false;
        }


        // Validate email (nếu không rỗng)
        if (!email.isEmpty()) {
            String regexEmail = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
            if (!email.matches(regexEmail)) {
                showError("Email không hợp lệ!", 500, 200);
                return false;
            }
        }

        // Validate số điện thoại VN
        // VN: 10 số, bắt đầu bằng 0
        String regexPhone = "^0\\d{9}$";
        if (!phone.matches(regexPhone)) {
            showError("Số điện thoại không hợp lệ!", 500, 200);
            return false;
        }

        return true;
    }

    public static String formatName(String name) {
        if (name == null || name.trim().isEmpty()) {
            return "";
        }

        // Xóa khoảng trắng dư
        name = name.trim().replaceAll("\\s+", " ");

        StringBuilder result = new StringBuilder();

        for (String word : name.split(" ")) {
            if (!word.isEmpty()) {
                String first = word.substring(0, 1).toUpperCase();
                String rest = word.substring(1).toLowerCase();
                result.append(first).append(rest).append(" ");
            }
        }

        return result.toString().trim();
    }

    private void showError(String s, int w, int h) {
        CustomDialog.showMessage(null, s, "Giá trị nhập không hợp lệ", CustomDialog.MessageType.ERROR, w, h);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrev = new iuh.fit.se.group1.ui.component.custom.Button();
        btnNext = new iuh.fit.se.group1.ui.component.custom.Button();
        pnl = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        txtCitizenIdOrPassport = new iuh.fit.se.group1.ui.component.custom.TextField();
        lbll4 = new javax.swing.JLabel();
        txtFullName = new iuh.fit.se.group1.ui.component.custom.TextField();
        lbl5 = new javax.swing.JLabel();
        txtEmail = new iuh.fit.se.group1.ui.component.custom.TextField();
        llbl6 = new javax.swing.JLabel();
        txtPhone = new iuh.fit.se.group1.ui.component.custom.TextField();
        txtDob = new iuh.fit.se.group1.ui.component.custom.TextField();
        lbl7 = new javax.swing.JLabel();
        rdoGender = new iuh.fit.se.group1.ui.component.booking2.GenderRadioButtons();

        setBackground(new java.awt.Color(255, 255, 255));

        btnPrev.setBackground(new java.awt.Color(227, 227, 227));
        btnPrev.setForeground(new java.awt.Color(77, 134, 168));
        btnPrev.setText("QUAY LẠI");
        btnPrev.setBorderRadius(5);
        btnPrev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnNext.setBackground(new java.awt.Color(77, 134, 168));
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("TIẾP THEO");
        btnNext.setBorderRadius(5);
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        pnl.setBackground(new java.awt.Color(185, 215, 254));

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setText("Nhập thông tin khách hàng");

        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 0));
        lbl2.setText("Vui lòng nhập thông tin chính xác ");

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
                pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLayout.createSequentialGroup()
                                .addContainerGap(30, Short.MAX_VALUE)
                                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pnlLayout.setVerticalGroup(
                pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl2)
                                .addContainerGap(18, Short.MAX_VALUE))
        );

        lbl3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 0, 0));
        lbl3.setText("CCCD/Hộ chiếu:");

        txtCitizenIdOrPassport.setForeground(new java.awt.Color(0, 0, 0));
        txtCitizenIdOrPassport.setBorderColor(new java.awt.Color(102, 102, 102));
        txtCitizenIdOrPassport.setBorderRadius(5);
        txtCitizenIdOrPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCitizenIdOrPassportActionPerformed(evt);
            }
        });

        lbll4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbll4.setForeground(new java.awt.Color(0, 0, 0));
        lbll4.setText("Họ và tên:");

        txtFullName.setForeground(new java.awt.Color(0, 0, 0));
        txtFullName.setBorderColor(new java.awt.Color(102, 102, 102));
        txtFullName.setBorderRadius(5);
        txtFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullNameActionPerformed(evt);
            }
        });

        lbl5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl5.setForeground(new java.awt.Color(0, 0, 0));
        lbl5.setText("Email:");

        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setBorderColor(new java.awt.Color(102, 102, 102));
        txtEmail.setBorderRadius(5);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        llbl6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        llbl6.setForeground(new java.awt.Color(0, 0, 0));
        llbl6.setText("Số điện thoại:");

        txtPhone.setForeground(new java.awt.Color(0, 0, 0));
        txtPhone.setBorderColor(new java.awt.Color(102, 102, 102));
        txtPhone.setBorderRadius(5);
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        txtDob.setForeground(new java.awt.Color(0, 0, 0));
        txtDob.setBorderColor(new java.awt.Color(102, 102, 102));
        txtDob.setBorderRadius(5);
        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });

        lbl7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl7.setForeground(new java.awt.Color(0, 0, 0));
        lbl7.setText("Ngày sinh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(rdoGender, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(llbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(lbll4, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(txtFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(txtCitizenIdOrPassport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                                .addContainerGap(43, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCitizenIdOrPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbll4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(llbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rdoGender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCitizenIdOrPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCitizenIdOrPassportActionPerformed
        CustomerService customerService = new CustomerService();
        String citizenId = txtCitizenIdOrPassport.getText().trim();
        Customer existingCustomer = customerService.getCustomerByCitizenId(citizenId);
        if (existingCustomer != null) {
            txtFullName.setText(existingCustomer.getFullName());
            txtEmail.setText(existingCustomer.getEmail());
            txtPhone.setText(existingCustomer.getPhone());

            DateTimeFormatter outputFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            String dobStr = existingCustomer.getDateOfBirth().format(outputFormat);
            txtDob.setText(dobStr);

            rdoGender.setSelectedGender(existingCustomer.isGender());
            return;
        }
        txtFullName.requestFocus();
    }//GEN-LAST:event_txtCitizenIdOrPassportActionPerformed

    private void txtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullNameActionPerformed
        txtFullName.setText(formatName(txtFullName.getText()));

        txtEmail.requestFocus();
    }//GEN-LAST:event_txtFullNameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        txtPhone.requestFocus();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        txtDob.requestFocus();
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
    }//GEN-LAST:event_txtDobActionPerformed

    public boolean setupDob() {
        DateTimeFormatter inputFormat = DateTimeFormatter.ofPattern("ddMMyyyy");
        DateTimeFormatter outputFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String dob = txtDob.getText().trim();

        if (!validateDate(dob)) {
            return false;
        }

        if (dob.contains("/")) {
            dob = dob.replace("/", "");
        }


        LocalDate date = LocalDate.parse(dob, inputFormat);
        String rs = date.format(outputFormat);

        txtDob.setText(rs);
        return true;
    }

    public boolean validateDate(String date) {

        if (date == null || date.trim().isEmpty()) {
            showError("Ngày sinh không được để trống!", 500, 200);
            return false;
        }

        date = date.trim();

        // Nếu có dấu "/", bỏ để thành ddMMyyyy
        if (date.contains("/")) {
            date = date.replace("/", "");
        }

        if (!date.matches("\\d{8}")) {
            showError("Định dạng ngày sinh không hợp lệ (ddMMyyyy hoặc dd/MM/yyyy)!", 550, 200);
            return false;
        }

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("ddMMyyyy")
                .withResolverStyle(ResolverStyle.SMART);

        try {
            LocalDate dob = LocalDate.parse(date, formatter);

            if (dob.isAfter(LocalDate.now())) {
                showError("Ngày sinh không được ở tương lai!", 500, 200);
                return false;
            }

            if (dob.isBefore(LocalDate.now().minusYears(150))) {
                showError("Ngày sinh không hợp lệ (quá xa trong quá khứ)!", 500, 200);
                return false;
            }

            // ⭐️ Kiểm tra phải >= 18 tuổi
            if (dob.isAfter(LocalDate.now().minusYears(18))) {
                showError("Khách hàng phải từ 18 tuổi trở lên!", 500, 200);
                return false;
            }

        } catch (Exception e) {
            showError("Ngày sinh không hợp lệ!", 500, 200);
            return false;
        }
        return true;
    }


    public Customer getCustomer(){
        String citizenIdOrPassport = txtCitizenIdOrPassport.getText().trim();
        String fullName = txtFullName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();

        CustomerService customerService = new CustomerService();

        Customer customerSaveDB = customerService.getCustomerByCitizenId(citizenIdOrPassport);

        if (customerSaveDB != null) {
            boolean needUpdate = false;

            if (!customerSaveDB.getEmail().equals(email)) {
                customerSaveDB.setEmail(email);
                needUpdate = true;
            }

            if (!customerSaveDB.getPhone().equals(phone)) {
                customerSaveDB.setPhone(phone);
                needUpdate = true;
            }

            if (needUpdate) {
                return customerService.updateCustomer(customerSaveDB);
            }
            return customerSaveDB;
        }

        // Nếu chưa có trong DB → tạo mới
        Customer customer = new Customer();
        customer.setCitizenId(citizenIdOrPassport);
        customer.setFullName(formatName(fullName));
        customer.setEmail(email);
        customer.setPhone(phone);

        DateTimeFormatter inputFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dob = LocalDate.parse(txtDob.getText().trim(), inputFormat);

        customer.setDateOfBirth(dob);
        customer.setGender(rdoGender.getSelectedGender());

        return customer;
    }


    public void reset() {
        txtCitizenIdOrPassport.setText("");
        txtFullName.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        txtDob.setText("");
        rdoGender.setSelectedGender(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.Button btnNext;
    private iuh.fit.se.group1.ui.component.custom.Button btnPrev;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbll4;
    private javax.swing.JLabel llbl6;
    private javax.swing.JPanel pnl;
    private iuh.fit.se.group1.ui.component.booking2.GenderRadioButtons rdoGender;
    private iuh.fit.se.group1.ui.component.custom.TextField txtCitizenIdOrPassport;
    private iuh.fit.se.group1.ui.component.custom.TextField txtDob;
    private iuh.fit.se.group1.ui.component.custom.TextField txtEmail;
    private iuh.fit.se.group1.ui.component.custom.TextField txtFullName;
    private iuh.fit.se.group1.ui.component.custom.TextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
