package iuh.fit.se.group1.ui.component.booking2;

import iuh.fit.se.group1.dto.RoomDTO;
import iuh.fit.se.group1.dto.RoomSelection;
import iuh.fit.se.group1.dto.RoomViewDTO;
import iuh.fit.se.group1.entity.Room;
import iuh.fit.se.group1.entity.RoomType;
import iuh.fit.se.group1.enums.BookingType;
import iuh.fit.se.group1.service.RoomService;
import iuh.fit.se.group1.service.RoomTypeService;
import iuh.fit.se.group1.ui.component.custom.Button;
import iuh.fit.se.group1.ui.component.custom.message.CustomDialog;
import iuh.fit.se.group1.util.Constants;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import java.awt.*;
import java.util.LinkedHashMap;
import java.util.Map;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 * @author THIS PC
 */
public class MainFlow2 extends javax.swing.JPanel {
    public JLabel getLblTotalRoom() {
        return lblTotalRoom;
    }

    public void setLblTotalRoom(JLabel lblTotalRoom) {
        this.lblTotalRoom = lblTotalRoom;
    }

    private static final Logger log = LoggerFactory.getLogger(MainFlow2.class);

    /**
     * Creates new form MainFlow2
     */
    public MainFlow2() {
        initComponents();
        String text =
                "<html>"
                        + "<span>Chọn phòng phù hợp với nhu cầu</span><br>"
                        + "<u>Lưu ý :</u><br>"
                        + "<ul>"
                        + "  <li>Người dưới 12 tuổi được tính là <b>trẻ em</b></li>"
                        + "  <li>Phòng đơn có thể chứa tối đa 2 người lớn + 1 trẻ em</li>"
                        + "  <li>Phòng đôi có thể chứa tối đa 4 người lớn + 2 trẻ em</li>"
                        + "  <li>Đề xuất cho khách hàng XXX : 4 phòng đơn + 2 phòng đôi</li>"
                        + "</ul>"
                        + "</html>";

        lbl1.setText(text);

        // JScroll pane không hiện kéo
        scr.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scr.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        btnNext = new iuh.fit.se.group1.ui.component.custom.Button();
        btnPrev = new iuh.fit.se.group1.ui.component.custom.Button();
        scr = new javax.swing.JScrollPane();
        tbl = new iuh.fit.se.group1.ui.component.booking2.CustomTable();
        lblMessage = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lblTotalRoom = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pnl1.setBackground(new java.awt.Color(185, 215, 254));

        lbl2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 0));
        lbl2.setText("Chọn phòng");

        lbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setText("Chọn phòng phù hợp với nhu cầu:");

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
                pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(48, Short.MAX_VALUE))
        );
        pnl1Layout.setVerticalGroup(
                pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lbl2)
                                .addGap(7, 7, 7)
                                .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addContainerGap())
        );

        btnNext.setBackground(new java.awt.Color(77, 134, 168));
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("TIẾP THEO");
        btnNext.setBorderRadius(5);
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setBackground(new java.awt.Color(227, 227, 227));
        btnPrev.setForeground(new java.awt.Color(77, 134, 168));
        btnPrev.setText("QUAY LẠI");
        btnPrev.setBorderRadius(5);
        btnPrev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        tbl.setBackground(new java.awt.Color(255, 255, 255));
        tbl.setForeground(new java.awt.Color(51, 51, 51));
        scr.setViewportView(tbl);

        lblMessage.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 0, 0));
        lblMessage.setText("Số khách chưa được xếp");

        lbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl.setForeground(new java.awt.Color(0, 0, 0));
        lbl.setText("Tổng tiền:");

        lblTotalRoom.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTotalRoom.setForeground(new java.awt.Color(255, 0, 0));
        lblTotalRoom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalRoom.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 480, Short.MAX_VALUE)
                                                .addComponent(lblTotalRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(scr)
                                                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scr, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTotalRoom))
                                .addGap(1, 1, 1)
                                .addComponent(lblMessage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    public Button getBtnNext() {
        return btnNext;
    }

    public void setBtnNext(Button btnNext) {
        this.btnNext = btnNext;
    }

    public Button getBtnPrev() {
        return btnPrev;
    }

    public void setBtnPrev(Button btnPrev) {

        this.btnPrev = btnPrev;
    }


    public Long getPriceFromBookingTypeAndRoomType(int bookingType, RoomDTO roomDTO, int timePlus) {
        if (bookingType == 0) { // Theo giờ
            return roomDTO.getHourlyRate().longValueExact() + ((timePlus - 1) * roomDTO.getAdditionalHourRate().longValueExact());
        } else if (bookingType == 1) { // Theo ngày
            return roomDTO.getDailyRate().longValueExact() * timePlus;
        } else if (bookingType == 2) { // qua đêm
            return roomDTO.getOvernightRate().longValueExact();
        }
        return 0L;
    }

    public boolean updateRoomList(Map<RoomDTO, Long> availableRooms, int adults, int children, RoomService roomService, int bookingIndex, int timePlus) {
        long singleQuantity = 0;
        long doubleQuantity = 0;

        for (Map.Entry<RoomDTO, Long> entry : availableRooms.entrySet()) {
            RoomDTO room = entry.getKey();
            Long quantity = entry.getValue();

            if ("SINGLE".equals(room.getRoomType())) {
                singleQuantity = quantity;
            } else if ("DOUBLE".equals(room.getRoomType())) {
                doubleQuantity = quantity;
            }
        }

        Map<String, Long> optimizeRoomAllocation = roomService.optimizeRoomAllocation((int) singleQuantity, (int) doubleQuantity, adults, children);

        if (optimizeRoomAllocation.get("unaccommodatedGuests") > 0) {
            CustomDialog.showMessage(this, "Không đủ phòng để đáp ứng số lượng khách!", "Không đủ phòng", CustomDialog.MessageType.ERROR, 500, 200);
            return false;
        }

        var model = (CustomTable.CustomTableModel) tbl.getModel();
        int row = 0;
        for (Map.Entry<RoomDTO, Long> entry : availableRooms.entrySet()) {
            RoomDTO roomDTO = entry.getKey();
            Long quantity = entry.getValue();
            model.setValueAt(roomDTO.getRoomType().equals("SINGLE") ? "Phòng đơn" : "Phòng đôi", row, 0);
            model.setValueAt(roomDTO.getCapacity(), row, 1);

            model.setValueAt(getPriceFromBookingTypeAndRoomType(bookingIndex, roomDTO, timePlus), row, 2);

            // Cột 3 là tính tiền nên không set

            model.setValueAt(quantity, row, 4);

            if (roomDTO.getRoomType().equals("SINGLE")) {
                model.setValueAt(optimizeRoomAllocation.get("usedSingleRooms"), row, 5);
            } else if (roomDTO.getRoomType().equals("DOUBLE")) {
                model.setValueAt(optimizeRoomAllocation.get("usedDoubleRooms"), row, 5);
            }
            row++;
        }

        int unaccommodatedGuests = optimizeRoomAllocation.get("unaccommodatedGuests").intValue();

        if (unaccommodatedGuests > 0) {

            int unaccommodatedAdults = optimizeRoomAllocation.get("unaccommodatedAdults").intValue();
            int unaccommodatedChildren = optimizeRoomAllocation.get("unaccommodatedChildren").intValue();

            String msg;

            if (unaccommodatedChildren > 0) {
                msg = "Số khách chưa được xếp: " + unaccommodatedGuests +
                        " (Người lớn: " + unaccommodatedAdults +
                        ", Trẻ em: " + unaccommodatedChildren + ")";
            } else {
                msg = "Số khách chưa được xếp: " + unaccommodatedGuests +
                        " (Người lớn: " + unaccommodatedAdults + ")";
            }

            lblMessage.setText(msg);
            lblMessage.setForeground(Color.RED);

        } else {
            lblMessage.setText("Tất cả khách đã được xếp phòng.");
            lblMessage.setForeground(new Color(0, 153, 0));

        }


        lblTotalRoom.setText(getTotalPriceRoom((Number) tbl.getValueAt(0, 3), (Number) tbl.getValueAt(1, 3)));

        tbl.setQuantityChangeListener((r, newQuantity) -> {
            Map<String, Integer> rs = roomService.checkRoomCapacity(adults,
                    children,
                    (Number) tbl.getValueAt(0, 5),
                    (Number) tbl.getValueAt(1, 5));

            int leftoverAdults = rs.get("leftoverAdults");
            int leftoverChildren = rs.get("leftoverChildren");
            int leftoverTotal = leftoverAdults + leftoverChildren;

            String message;

            if (leftoverTotal == 0) {
                message = "Tất cả khách đã được xếp phòng hợp lý.";
                lblMessage.setForeground(new Color(0, 128, 0)); // màu xanh
            } else {
                if (leftoverChildren > 0) {
                    message = "Số khách chưa được xếp: " + leftoverTotal +
                            " (Người lớn: " + leftoverAdults +
                            ", Trẻ em: " + leftoverChildren + ")";
                } else {
                    message = "Số khách chưa được xếp: " + leftoverTotal +
                            " (Người lớn: " + leftoverAdults + ")";
                }

                lblMessage.setForeground(Color.RED);
            }

            lblMessage.setText(message);
            lblTotalRoom.setText(getTotalPriceRoom((Number) tbl.getValueAt(0, 3), (Number) tbl.getValueAt(1, 3)));
        });
        return true;
    }

    public String getTotalPriceRoom(Number priceSingle, Number priceDouble) {
        Long totalPrice = priceSingle.longValue() + priceDouble.longValue();
        return Constants.VND_FORMAT.format(totalPrice);

    }

    public java.util.List<RoomSelection> getSelectedRoom(java.util.List<RoomViewDTO> availableRooms) {

        int countSingleRoom = tbl.getValueAt(0, 5) != null ? ((Number) tbl.getValueAt(0, 5)).intValue() : 0;
        int countDoubleRoom = tbl.getValueAt(1, 5) != null ? ((Number) tbl.getValueAt(1, 5)).intValue() : 0;

        java.util.List<RoomSelection> selectedRooms = new java.util.ArrayList<>();


        for (RoomViewDTO room : availableRooms) {
            if (room.getRoomType().getRoomTypeId().equals("SINGLE") && countSingleRoom > 0) {
                selectedRooms.add(new RoomSelection(room.getRoomId(), room.getRoomNumber(), room.getRoomType().getRoomTypeId()));
                countSingleRoom--;
            } else if (room.getRoomType().getRoomTypeId().equals("DOUBLE") && countDoubleRoom > 0) {
                selectedRooms.add(new RoomSelection(room.getRoomId(), room.getRoomNumber(), room.getRoomType().getRoomTypeId()));
                countDoubleRoom--;
            }
            if (countSingleRoom == 0 && countDoubleRoom == 0) {
                break;
            }
        }
        return selectedRooms;
    }


    public void reset() {
        lblMessage.setText("Số khách chưa được xếp");
        lblMessage.setForeground(new Color(255, 0, 0));
        lblTotalRoom.setText("");
        var model = (CustomTable.CustomTableModel) tbl.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            model.setValueAt(0, i, 5); // reset số lượng đã chọn về 0
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.Button btnNext;
    private iuh.fit.se.group1.ui.component.custom.Button btnPrev;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTotalRoom;
    private javax.swing.JPanel pnl1;
    private javax.swing.JScrollPane scr;
    private iuh.fit.se.group1.ui.component.booking2.CustomTable tbl;
    // End of variables declaration//GEN-END:variables
}
