/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.booking2;

import iuh.fit.se.group1.dto.AmenityDTO;
import iuh.fit.se.group1.dto.OrderResult;
import iuh.fit.se.group1.dto.RoomSelection;
import iuh.fit.se.group1.entity.*;
import iuh.fit.se.group1.enums.BookingType;
import iuh.fit.se.group1.service.SurchargeDetailService;
import iuh.fit.se.group1.service.SurchargeService;
import iuh.fit.se.group1.ui.component.custom.Button;
import iuh.fit.se.group1.util.Constants;

import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * @author THIS PC
 */
public class MainFlow5 extends javax.swing.JPanel {

    private static final long SURCHARGE_HOLIDAY = 50_000;

    public Button getBtnPrev() {
        return btnPrev;
    }

    public Button getBtnComplete() {
        return btnComplete;
    }

    public void setBtnComplete(Button btnComplete) {
        this.btnComplete = btnComplete;
    }

    public void setBtnPrev(Button btnPrev) {
        this.btnPrev = btnPrev;
    }

    /**
     * Creates new form MainFlow5
     */
    public MainFlow5() {
        initComponents();
        tbl.setGridColor(new Color(10, 10, 10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        lblCheckIn = new javax.swing.JLabel();
        spn1 = new javax.swing.JSeparator();
        lbl4 = new javax.swing.JLabel();
        lblCheckOut = new javax.swing.JLabel();
        spn2 = new javax.swing.JSeparator();
        lbl5 = new javax.swing.JLabel();
        lblNumberOfAdult = new javax.swing.JLabel();
        spn3 = new javax.swing.JSeparator();
        lbl6 = new javax.swing.JLabel();
        lblDoubleRooms = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lblSingleRooms = new javax.swing.JLabel();
        spn4 = new javax.swing.JSeparator();
        lbl8 = new javax.swing.JLabel();
        lblNumberOfChildren = new javax.swing.JLabel();
        spn5 = new javax.swing.JSeparator();
        lbl20 = new javax.swing.JLabel();
        lblBookingType = new javax.swing.JLabel();
        spn6 = new javax.swing.JSeparator();
        pnl3 = new javax.swing.JPanel();
        lbl18 = new javax.swing.JLabel();
        lblTotalRoom = new javax.swing.JLabel();
        pnl4 = new javax.swing.JPanel();
        scr = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        pnl5 = new javax.swing.JPanel();
        lbl17 = new javax.swing.JLabel();
        lblTotalAmenity = new javax.swing.JLabel();
        pnl6 = new javax.swing.JPanel();
        lbl9 = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lblCitizenid = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        pnl7 = new javax.swing.JPanel();
        lbl15 = new javax.swing.JLabel();
        lbl16 = new javax.swing.JLabel();
        lblDeposit = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        btnComplete = new iuh.fit.se.group1.ui.component.custom.Button();
        btnPrev = new iuh.fit.se.group1.ui.component.custom.Button();
        lblSurchargeHolidayName = new javax.swing.JLabel();
        lblSurchargeHoliday = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pnl1.setBackground(new java.awt.Color(185, 215, 254));

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setText("Nhập thông tin khách hàng");

        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 0));
        lbl2.setText("Vui lòng nhập thông tin chính xác ");

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết đặt phòng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(102, 102, 102))); // NOI18N

        lbl3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl3.setForeground(new java.awt.Color(91, 91, 91));
        lbl3.setText("Ngày nhận phòng:");

        lblCheckIn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCheckIn.setForeground(new java.awt.Color(91, 91, 91));
        lblCheckIn.setText("n/a");

        spn1.setBackground(new java.awt.Color(91, 91, 91));
        spn1.setForeground(new java.awt.Color(91, 91, 91));
        spn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbl4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl4.setForeground(new java.awt.Color(91, 91, 91));
        lbl4.setText("Ngày trả phòng:");

        lblCheckOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCheckOut.setForeground(new java.awt.Color(91, 91, 91));
        lblCheckOut.setText("n/a");

        spn2.setBackground(new java.awt.Color(91, 91, 91));
        spn2.setForeground(new java.awt.Color(91, 91, 91));
        spn2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbl5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl5.setForeground(new java.awt.Color(91, 91, 91));
        lbl5.setText("Số người lớn:");

        lblNumberOfAdult.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumberOfAdult.setForeground(new java.awt.Color(91, 91, 91));
        lblNumberOfAdult.setText("n/a");

        spn3.setBackground(new java.awt.Color(91, 91, 91));
        spn3.setForeground(new java.awt.Color(91, 91, 91));
        spn3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbl6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl6.setForeground(new java.awt.Color(91, 91, 91));
        lbl6.setText("Phòng đôi:");

        lblDoubleRooms.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDoubleRooms.setForeground(new java.awt.Color(91, 91, 91));
        lblDoubleRooms.setText("n/a");

        lbl7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl7.setForeground(new java.awt.Color(91, 91, 91));
        lbl7.setText("Phòng đơn:");

        lblSingleRooms.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSingleRooms.setForeground(new java.awt.Color(91, 91, 91));
        lblSingleRooms.setText("n/a");

        spn4.setBackground(new java.awt.Color(91, 91, 91));
        spn4.setForeground(new java.awt.Color(91, 91, 91));
        spn4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbl8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl8.setForeground(new java.awt.Color(91, 91, 91));
        lbl8.setText("Số trẻ em:");

        lblNumberOfChildren.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumberOfChildren.setForeground(new java.awt.Color(91, 91, 91));
        lblNumberOfChildren.setText("n/a");

        spn5.setBackground(new java.awt.Color(91, 91, 91));
        spn5.setForeground(new java.awt.Color(91, 91, 91));
        spn5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbl20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl20.setForeground(new java.awt.Color(91, 91, 91));
        lbl20.setText("Kiểu đặt phòng");

        lblBookingType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBookingType.setForeground(new java.awt.Color(91, 91, 91));
        lblBookingType.setText("n/a");

        spn6.setBackground(new java.awt.Color(91, 91, 91));
        spn6.setForeground(new java.awt.Color(91, 91, 91));
        spn6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addComponent(lbl20, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBookingType, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spn6, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDoubleRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumberOfAdult, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spn2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spn1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spn3, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spn5, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumberOfChildren, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spn4, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSingleRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(lblCheckIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4)
                    .addComponent(lblCheckOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl5)
                    .addComponent(lblNumberOfAdult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl8)
                    .addComponent(lblNumberOfChildren))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl7)
                    .addComponent(lblSingleRooms))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl6)
                    .addComponent(lblDoubleRooms))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl20)
                    .addComponent(lblBookingType))
                .addContainerGap())
        );

        pnl3.setBackground(new java.awt.Color(185, 215, 254));

        lbl18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl18.setForeground(new java.awt.Color(0, 0, 0));
        lbl18.setText("Thành tiền phòng");

        lblTotalRoom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalRoom.setForeground(new java.awt.Color(77, 134, 168));
        lblTotalRoom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalRoom.setText("n/a");

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl18, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(lblTotalRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl4.setBackground(new java.awt.Color(255, 255, 255));
        pnl4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dịch vụ bổ sung", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        pnl4.setForeground(new java.awt.Color(255, 255, 255));

        scr.setBackground(new java.awt.Color(255, 255, 255));

        tbl.setBackground(new java.awt.Color(255, 255, 255));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Tên dịch vụ", "Giá", "Số lượng"
            }
        ));
        tbl.getTableHeader().setReorderingAllowed(false);
        scr.setViewportView(tbl);

        javax.swing.GroupLayout pnl4Layout = new javax.swing.GroupLayout(pnl4);
        pnl4.setLayout(pnl4Layout);
        pnl4Layout.setHorizontalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scr)
                .addContainerGap())
        );
        pnl4Layout.setVerticalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl5.setBackground(new java.awt.Color(185, 215, 254));

        lbl17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl17.setForeground(new java.awt.Color(0, 0, 0));
        lbl17.setText("Thành tiền dịch vụ");

        lblTotalAmenity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalAmenity.setForeground(new java.awt.Color(77, 134, 168));
        lblTotalAmenity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalAmenity.setText("n/a");

        javax.swing.GroupLayout pnl5Layout = new javax.swing.GroupLayout(pnl5);
        pnl5.setLayout(pnl5Layout);
        pnl5Layout.setHorizontalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl17, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(lblTotalAmenity, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        pnl5Layout.setVerticalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalAmenity, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl6.setBackground(new java.awt.Color(255, 255, 255));
        pnl6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(102, 102, 102))); // NOI18N

        lbl9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl9.setForeground(new java.awt.Color(91, 91, 91));
        lbl9.setText("Họ và tên:");

        lblFullName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(91, 91, 91));
        lblFullName.setText("n/a");

        lbl10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl10.setForeground(new java.awt.Color(91, 91, 91));
        lbl10.setText("Số điện thoại:");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(91, 91, 91));
        lblPhone.setText("n/a");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(91, 91, 91));
        lblEmail.setText("n/a");

        lbl11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl11.setForeground(new java.awt.Color(91, 91, 91));
        lbl11.setText("Email:");

        lblCitizenid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCitizenid.setForeground(new java.awt.Color(91, 91, 91));
        lblCitizenid.setText("n/a");

        lbl12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl12.setForeground(new java.awt.Color(91, 91, 91));
        lbl12.setText("Ngày sinh:");

        lbl14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl14.setForeground(new java.awt.Color(91, 91, 91));
        lbl14.setText("CCCD/Hộ chiếu:");

        lblDob.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDob.setForeground(new java.awt.Color(91, 91, 91));
        lblDob.setText("n/a");

        lbl13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl13.setForeground(new java.awt.Color(91, 91, 91));
        lbl13.setText("Giới tính:");

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGender.setForeground(new java.awt.Color(91, 91, 91));
        lblGender.setText("n/a");

        javax.swing.GroupLayout pnl6Layout = new javax.swing.GroupLayout(pnl6);
        pnl6.setLayout(pnl6Layout);
        pnl6Layout.setHorizontalGroup(
            pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl6Layout.createSequentialGroup()
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl6Layout.createSequentialGroup()
                                    .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnl6Layout.createSequentialGroup()
                                    .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl6Layout.createSequentialGroup()
                                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl14, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl6Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDob, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCitizenid, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 106, Short.MAX_VALUE))
        );
        pnl6Layout.setVerticalGroup(
            pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl9)
                    .addComponent(lblFullName))
                .addGap(10, 10, 10)
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl10)
                    .addComponent(lblPhone))
                .addGap(10, 10, 10)
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl11)
                    .addComponent(lblEmail))
                .addGap(10, 10, 10)
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCitizenid)
                    .addComponent(lbl14))
                .addGap(10, 10, 10)
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl12)
                    .addComponent(lblDob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl13)
                    .addComponent(lblGender))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnl7.setBackground(new java.awt.Color(153, 255, 153));

        lbl15.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl15.setForeground(new java.awt.Color(91, 91, 91));
        lbl15.setText("Tổng thanh toán:");

        lbl16.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl16.setForeground(new java.awt.Color(91, 91, 91));
        lbl16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl16.setText("Đặt cọc 30% tiền phòng");

        lblDeposit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDeposit.setForeground(new java.awt.Color(251, 128, 5));
        lblDeposit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeposit.setText("N/A");

        lblTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(0, 153, 51));
        lblTotalPrice.setText("N/A");

        javax.swing.GroupLayout pnl7Layout = new javax.swing.GroupLayout(pnl7);
        pnl7.setLayout(pnl7Layout);
        pnl7Layout.setHorizontalGroup(
            pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl16, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(lblDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        pnl7Layout.setVerticalGroup(
            pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl15)
                    .addComponent(lbl16))
                .addGap(0, 0, 0)
                .addGroup(pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        btnComplete.setBackground(new java.awt.Color(13, 200, 7));
        btnComplete.setForeground(new java.awt.Color(255, 255, 255));
        btnComplete.setText("XÁC NHẬN ĐẶT PHÒNG");
        btnComplete.setBorderRadius(5);
        btnComplete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        btnPrev.setBackground(new java.awt.Color(227, 227, 227));
        btnPrev.setForeground(new java.awt.Color(77, 134, 168));
        btnPrev.setText("QUAY LẠI");
        btnPrev.setBorderRadius(5);
        btnPrev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        lblSurchargeHolidayName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSurchargeHolidayName.setForeground(new java.awt.Color(255, 51, 51));
        lblSurchargeHolidayName.setText("Phụ thu ngày lễ");

        lblSurchargeHoliday.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblSurchargeHoliday.setForeground(new java.awt.Color(255, 0, 0));
        lblSurchargeHoliday.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSurchargeHoliday.setText("N/a");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSurchargeHolidayName, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSurchargeHoliday, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurchargeHolidayName)
                    .addComponent(lblSurchargeHoliday))
                .addGap(18, 18, 18)
                .addComponent(pnl7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCompleteActionPerformed


    public void setAmenity(List<AmenityDTO> selectedAmenities) {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
        int index = 1;
        BigDecimal total = BigDecimal.ZERO;
        for (AmenityDTO amenity : selectedAmenities) {
            Object[] row = new Object[]{
                    index++,
                    amenity.getName(),
                    Constants.VND_FORMAT.format(amenity.getPrice()),
                    amenity.getQuantity()
            };
            total = total.add(BigDecimal.valueOf(amenity.getPrice() * amenity.getQuantity()));
            model.addRow(row);
        }
        lblTotalAmenity.setText(Constants.VND_FORMAT.format(total));
    }

    public void setupCustomer(Customer customer) {
        lblFullName.setText(customer.getFullName());
        lblPhone.setText(customer.getPhone());
        lblEmail.setText(customer.getEmail() != null ? customer.getEmail() : "N/A");
        lblCitizenid.setText(customer.getCitizenId());
        lblDob.setText(customer.getDateOfBirth().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        lblGender.setText(customer.isGender() ? "Nữ" : "Nam");
    }

    public void setInfoBooking(
            String checkIn,
            String checkOut,
            String numberOfAdult,
            String numberOfChildren,
            String bookingType,
            List<RoomSelection> selectedRoom,
            String totalRoom,
            boolean isHoliday
    ) {

        lblCheckIn.setText(checkIn);
        lblCheckOut.setText(checkOut);
        lblNumberOfAdult.setText(numberOfAdult);
        lblNumberOfChildren.setText(numberOfChildren);
        lblBookingType.setText(bookingType);
        lblTotalRoom.setText(totalRoom);

        Map<String, List<RoomSelection>> map = selectedRoom.stream()
                .collect(Collectors.groupingBy(RoomSelection::getRoomType));

        for (Map.Entry<String, List<RoomSelection>> entry : map.entrySet()) {
            String roomTypeKey = entry.getKey();
            var listRoom = entry.getValue();
            String valueNew = listRoom.stream()
                    .map(RoomSelection::getNumber)
                    .collect(Collectors.joining(", "));
            if (roomTypeKey.equals("SINGLE")) {
                lblSingleRooms.setText(valueNew);
            } else if (roomTypeKey.equals("DOUBLE")) {
                lblDoubleRooms.setText(valueNew);
            }
        }

        var deposit = Constants.parseVND(totalRoom) * 0.3;
        lblDeposit.setText(Constants.VND_FORMAT.format(deposit));


        var holidayPrice = isHoliday ? SURCHARGE_HOLIDAY * selectedRoom.size() : 0;

        var totalPrice = Constants.parseVND(totalRoom) + Constants.parseVND(lblTotalAmenity.getText());


        lblSurchargeHoliday.setText(holidayPrice != 0 ? Constants.VND_FORMAT.format(holidayPrice) : "Không có");

        lblTotalPrice.setText(Constants.VND_FORMAT.format(totalPrice + holidayPrice));
    }


    public OrderResult buildOrder(
            Employee currentEmployee,
            Customer customer,
            List<RoomSelection> selectedRooms,
            SurchargeService surchargeService) {

        Order order = new Order();
        order.setCustomer(customer);
        order.setDeposit(BigDecimal.valueOf(Constants.parseVND(lblDeposit.getText())));
        order.setOrderDate(LocalDateTime.now());
        order.setTotalAmount(BigDecimal.valueOf(Constants.parseVND(lblTotalPrice.getText())));
        order.setEmployee(currentEmployee);

        order.setOrderType(new OrderType());

        LocalDateTime checkIn = LocalDateTime.parse(
                lblCheckIn.getText(),
                DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")
        );
        LocalDateTime checkOut = LocalDateTime.parse(
                lblCheckOut.getText(),
                DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")
        );



        LocalDateTime now = LocalDateTime.now();

        // Nếu checkIn trước now + 1 giờ → đặt trước
        if (!checkIn.isBefore(now.plusHours(1))) {
            order.setOrderType(new OrderType(3L)); // loại đặt trước
        } else {
            order.setOrderType(new OrderType(2L)); // loại ở ngay
        }

        List<Booking> bookings = new ArrayList<>();

        for (RoomSelection roomSelection : selectedRooms) {
            Booking booking = new Booking();
            booking.setRoom(new Room(roomSelection.getId()));
            booking.setCheckInDate(checkIn);
            booking.setCheckOutDate(checkOut);
            booking.setBookingType(BookingType.fromString(lblBookingType.getText()));
            bookings.add(booking);
        }

        order.setBookings(bookings);


        if (lblSurchargeHoliday.getText().equals("N/a") || lblSurchargeHoliday.getText().equals("Không có")) {
            return new OrderResult(order,null);
        }

        Surcharge surchargeHoliday = surchargeService.getSurchargeByName(lblSurchargeHolidayName.getText().trim());

        SurchargeDetail surchargeDetail = new SurchargeDetail();
        surchargeDetail.setSurcharge(surchargeHoliday);
        surchargeDetail.setQuantity(selectedRooms.size());

        return new OrderResult(order,surchargeDetail);

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.Button btnComplete;
    private iuh.fit.se.group1.ui.component.custom.Button btnPrev;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblBookingType;
    private javax.swing.JLabel lblCheckIn;
    private javax.swing.JLabel lblCheckOut;
    private javax.swing.JLabel lblCitizenid;
    private javax.swing.JLabel lblDeposit;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblDoubleRooms;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblNumberOfAdult;
    private javax.swing.JLabel lblNumberOfChildren;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSingleRooms;
    private javax.swing.JLabel lblSurchargeHoliday;
    private javax.swing.JLabel lblSurchargeHolidayName;
    private javax.swing.JLabel lblTotalAmenity;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblTotalRoom;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl4;
    private javax.swing.JPanel pnl5;
    private javax.swing.JPanel pnl6;
    private javax.swing.JPanel pnl7;
    private javax.swing.JScrollPane scr;
    private javax.swing.JSeparator spn1;
    private javax.swing.JSeparator spn2;
    private javax.swing.JSeparator spn3;
    private javax.swing.JSeparator spn4;
    private javax.swing.JSeparator spn5;
    private javax.swing.JSeparator spn6;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
