/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.paymentv2;

import iuh.fit.se.group1.dto.SurchargeDTO;
import iuh.fit.se.group1.enums.PaymentType;
import iuh.fit.se.group1.service.*;
import iuh.fit.se.group1.dto.AmenityDTO;
import iuh.fit.se.group1.dto.RoomSelection;
import iuh.fit.se.group1.entity.*;
import iuh.fit.se.group1.ui.component.custom.Button;
import iuh.fit.se.group1.ui.component.custom.message.CustomDialog;
import iuh.fit.se.group1.ui.component.payment.CashPaymentModal;
import iuh.fit.se.group1.ui.component.payment.TransferPaymentModal;
import iuh.fit.se.group1.util.Constants;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import raven.glasspanepopup.GlassPanePopup;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * @author THIS PC
 */
public class PaymentMain extends javax.swing.JPanel {

    private OrderService orderService;
    private Order currentOrder = null;

    private SurchargeService surchargeService = new SurchargeService();
    private SurchargeDetailService surchargeDetailService = new SurchargeDetailService();
    private static final long SURCHARGE_HOLIDAY = 50_000;
    private static final Logger log = LoggerFactory.getLogger(PaymentMain.class);
    private Promotion promotion = null;

    public Button getBtnPrev() {
        return btnPrev;
    }


    public void setBtnPrev(Button btnPrev) {
        this.btnPrev = btnPrev;
    }

    /**
     * Creates new form MainFlow5
     */
    public PaymentMain() {
        initComponents();
        tblAmenity.setGridColor(new Color(10, 10, 10));
        tblAmenity.getTableHeader().setReorderingAllowed(false); // Không cho kéo đổi vị trí cột
        tblAmenity.getTableHeader().setResizingAllowed(false);   // Không cho resize cột
        tblSurcharge.getTableHeader().setReorderingAllowed(false); // Không cho kéo đổi vị trí cột
        tblSurcharge.getTableHeader().setResizingAllowed(false);   // Không cho resize cột
        ((DefaultTableModel) tblAmenity.getModel()).setRowCount(0);
        tblAmenity.setDefaultEditor(Object.class, null);

        ((DefaultTableModel) tblSurcharge.getModel()).setRowCount(0);
        tblSurcharge.setDefaultEditor(Object.class, null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        lblCheckIn = new javax.swing.JLabel();
        spn1 = new javax.swing.JSeparator();
        lbl4 = new javax.swing.JLabel();
        lblCheckOut = new javax.swing.JLabel();
        spn2 = new javax.swing.JSeparator();
        lbl6 = new javax.swing.JLabel();
        lblDoubleRooms = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lblSingleRooms = new javax.swing.JLabel();
        spn4 = new javax.swing.JSeparator();
        lbl20 = new javax.swing.JLabel();
        lblBookingType = new javax.swing.JLabel();
        spn6 = new javax.swing.JSeparator();
        pnl3 = new javax.swing.JPanel();
        lbl18 = new javax.swing.JLabel();
        lblTotalRoom = new javax.swing.JLabel();
        pnl4 = new javax.swing.JPanel();
        scr = new javax.swing.JScrollPane();
        tblAmenity = new javax.swing.JTable();
        pnl5 = new javax.swing.JPanel();
        lbl17 = new javax.swing.JLabel();
        lblTotalAmenity = new javax.swing.JLabel();
        pnl6 = new javax.swing.JPanel();
        lbl9 = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lblCitizenid = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        btnPrev = new iuh.fit.se.group1.ui.component.custom.Button();
        pnl31 = new javax.swing.JPanel();
        scr1 = new javax.swing.JScrollPane();
        tblSurcharge = new javax.swing.JTable();
        pnl9 = new javax.swing.JPanel();
        lbl21 = new javax.swing.JLabel();
        lblTotalSurcharge = new javax.swing.JLabel();
        btnAddSurcharge = new iuh.fit.se.group1.ui.component.custom.Button();
        lbl932 = new javax.swing.JLabel();
        lblPromotionName = new javax.swing.JLabel();
        lblPromotion = new javax.swing.JLabel();
        lbl16 = new javax.swing.JLabel();
        lblDeposit = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        lblTotalPricePayment = new javax.swing.JLabel();
        btnCash = new iuh.fit.se.group1.ui.component.custom.Button();
        bntTranfer = new iuh.fit.se.group1.ui.component.custom.Button();

        setBackground(new java.awt.Color(255, 255, 255));

        pnl1.setBackground(new java.awt.Color(185, 215, 254));

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setText("Xác nhận thông tin chính xác trước khi thanh toán");

        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 0));
        lbl2.setText("Kiểm tra phụ phí và dịch vụ đi kèm");

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết đặt phòng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(102, 102, 102))); // NOI18N

        lbl3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl3.setForeground(new java.awt.Color(91, 91, 91));
        lbl3.setText("Ngày nhận phòng:");

        lblCheckIn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCheckIn.setForeground(new java.awt.Color(91, 91, 91));
        lblCheckIn.setText("n/a");

        spn1.setBackground(new java.awt.Color(91, 91, 91));
        spn1.setForeground(new java.awt.Color(91, 91, 91));
        spn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbl4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl4.setForeground(new java.awt.Color(91, 91, 91));
        lbl4.setText("Ngày trả phòng:");

        lblCheckOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCheckOut.setForeground(new java.awt.Color(91, 91, 91));
        lblCheckOut.setText("n/a");

        spn2.setBackground(new java.awt.Color(91, 91, 91));
        spn2.setForeground(new java.awt.Color(91, 91, 91));
        spn2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbl6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl6.setForeground(new java.awt.Color(91, 91, 91));
        lbl6.setText("Phòng đôi:");

        lblDoubleRooms.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDoubleRooms.setForeground(new java.awt.Color(91, 91, 91));
        lblDoubleRooms.setText("0");

        lbl7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl7.setForeground(new java.awt.Color(91, 91, 91));
        lbl7.setText("Phòng đơn:");

        lblSingleRooms.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSingleRooms.setForeground(new java.awt.Color(91, 91, 91));
        lblSingleRooms.setText("0");

        spn4.setBackground(new java.awt.Color(91, 91, 91));
        spn4.setForeground(new java.awt.Color(91, 91, 91));
        spn4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbl20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl20.setForeground(new java.awt.Color(91, 91, 91));
        lbl20.setText("Kiểu đặt phòng");

        lblBookingType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBookingType.setForeground(new java.awt.Color(91, 91, 91));
        lblBookingType.setText("n/a");

        spn6.setBackground(new java.awt.Color(91, 91, 91));
        spn6.setForeground(new java.awt.Color(91, 91, 91));
        spn6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl2Layout.createSequentialGroup()
                                .addComponent(lbl20, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBookingType, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl2Layout.createSequentialGroup()
                                .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDoubleRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl2Layout.createSequentialGroup()
                                .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl2Layout.createSequentialGroup()
                                .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSingleRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addComponent(spn2)
                    .addComponent(spn1)
                    .addComponent(spn4)
                    .addComponent(spn6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(lblCheckIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4)
                    .addComponent(lblCheckOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl7)
                    .addComponent(lblSingleRooms))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl6)
                    .addComponent(lblDoubleRooms))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl20)
                    .addComponent(lblBookingType))
                .addContainerGap())
        );

        pnl3.setBackground(new java.awt.Color(185, 215, 254));

        lbl18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl18.setForeground(new java.awt.Color(0, 0, 0));
        lbl18.setText("Thành tiền phòng");

        lblTotalRoom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalRoom.setForeground(new java.awt.Color(77, 134, 168));
        lblTotalRoom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalRoom.setText("0");

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl18, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl4.setBackground(new java.awt.Color(255, 255, 255));
        pnl4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dịch vụ bổ sung", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        pnl4.setForeground(new java.awt.Color(255, 255, 255));

        scr.setBackground(new java.awt.Color(255, 255, 255));

        tblAmenity.setBackground(new java.awt.Color(255, 255, 255));
        tblAmenity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên dịch vụ", "Giá", "Số lượng"
            }
        ));
        tblAmenity.getTableHeader().setReorderingAllowed(false);
        scr.setViewportView(tblAmenity);

        javax.swing.GroupLayout pnl4Layout = new javax.swing.GroupLayout(pnl4);
        pnl4.setLayout(pnl4Layout);
        pnl4Layout.setHorizontalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scr, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl4Layout.setVerticalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl5.setBackground(new java.awt.Color(185, 215, 254));

        lbl17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl17.setForeground(new java.awt.Color(0, 0, 0));
        lbl17.setText("Thành tiền dịch vụ");

        lblTotalAmenity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalAmenity.setForeground(new java.awt.Color(77, 134, 168));
        lblTotalAmenity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalAmenity.setText("0");

        javax.swing.GroupLayout pnl5Layout = new javax.swing.GroupLayout(pnl5);
        pnl5.setLayout(pnl5Layout);
        pnl5Layout.setHorizontalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalAmenity, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl5Layout.setVerticalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalAmenity, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl6.setBackground(new java.awt.Color(255, 255, 255));
        pnl6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(102, 102, 102))); // NOI18N

        lbl9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl9.setForeground(new java.awt.Color(91, 91, 91));
        lbl9.setText("Họ và tên:");

        lblFullName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(91, 91, 91));
        lblFullName.setText("n/a");

        lbl10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl10.setForeground(new java.awt.Color(91, 91, 91));
        lbl10.setText("Số điện thoại:");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(91, 91, 91));
        lblPhone.setText("n/a");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(91, 91, 91));
        lblEmail.setText("n/a");

        lbl11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl11.setForeground(new java.awt.Color(91, 91, 91));
        lbl11.setText("Email:");

        lblCitizenid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCitizenid.setForeground(new java.awt.Color(91, 91, 91));
        lblCitizenid.setText("n/a");

        lbl12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl12.setForeground(new java.awt.Color(91, 91, 91));
        lbl12.setText("Ngày sinh:");

        lbl14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl14.setForeground(new java.awt.Color(91, 91, 91));
        lbl14.setText("CCCD/Hộ chiếu:");

        lblDob.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDob.setForeground(new java.awt.Color(91, 91, 91));
        lblDob.setText("n/a");

        lbl13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl13.setForeground(new java.awt.Color(91, 91, 91));
        lbl13.setText("Giới tính:");

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGender.setForeground(new java.awt.Color(91, 91, 91));
        lblGender.setText("n/a");

        javax.swing.GroupLayout pnl6Layout = new javax.swing.GroupLayout(pnl6);
        pnl6.setLayout(pnl6Layout);
        pnl6Layout.setHorizontalGroup(
            pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl6Layout.createSequentialGroup()
                        .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl6Layout.createSequentialGroup()
                        .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl6Layout.createSequentialGroup()
                        .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(pnl6Layout.createSequentialGroup()
                                    .addComponent(lbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)))
                            .addGroup(pnl6Layout.createSequentialGroup()
                                .addComponent(lbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)))
                        .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnl6Layout.createSequentialGroup()
                                    .addComponent(lblDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(3, 3, 3))
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCitizenid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl6Layout.setVerticalGroup(
            pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl9)
                    .addComponent(lblFullName))
                .addGap(10, 10, 10)
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl10)
                    .addComponent(lblPhone))
                .addGap(10, 10, 10)
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl11)
                    .addComponent(lblEmail))
                .addGap(10, 10, 10)
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCitizenid)
                    .addComponent(lbl14))
                .addGap(10, 10, 10)
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl12)
                    .addComponent(lblDob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl13)
                    .addComponent(lblGender))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        btnPrev.setBackground(new java.awt.Color(227, 227, 227));
        btnPrev.setForeground(new java.awt.Color(77, 134, 168));
        btnPrev.setText("QUAY LẠI");
        btnPrev.setBorderRadius(5);
        btnPrev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        pnl31.setBackground(new java.awt.Color(255, 255, 255));
        pnl31.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phụ phí", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        scr1.setBackground(new java.awt.Color(255, 255, 255));

        tblSurcharge.setBackground(new java.awt.Color(255, 255, 255));
        tblSurcharge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên phụ phí", "Giá", "Số lượng", "Tổng tiền"
            }
        ));
        tblSurcharge.getTableHeader().setReorderingAllowed(false);
        scr1.setViewportView(tblSurcharge);

        javax.swing.GroupLayout pnl31Layout = new javax.swing.GroupLayout(pnl31);
        pnl31.setLayout(pnl31Layout);
        pnl31Layout.setHorizontalGroup(
            pnl31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scr1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl31Layout.setVerticalGroup(
            pnl31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scr1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl9.setBackground(new java.awt.Color(185, 215, 254));

        lbl21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl21.setForeground(new java.awt.Color(0, 0, 0));
        lbl21.setText("Thành tiền phụ phí");

        lblTotalSurcharge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalSurcharge.setForeground(new java.awt.Color(77, 134, 168));
        lblTotalSurcharge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalSurcharge.setText("0");

        javax.swing.GroupLayout pnl9Layout = new javax.swing.GroupLayout(pnl9);
        pnl9.setLayout(pnl9Layout);
        pnl9Layout.setHorizontalGroup(
            pnl9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl21, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalSurcharge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl9Layout.setVerticalGroup(
            pnl9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalSurcharge, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnAddSurcharge.setBackground(new java.awt.Color(255, 0, 0));
        btnAddSurcharge.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSurcharge.setText("Thêm phụ phí");
        btnAddSurcharge.setBorderRadius(5);
        btnAddSurcharge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddSurcharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSurchargeActionPerformed(evt);
            }
        });

        lbl932.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl932.setForeground(new java.awt.Color(0, 0, 0));
        lbl932.setText("Khuyến mãi");

        lblPromotionName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblPromotionName.setForeground(new java.awt.Color(0, 0, 0));
        lblPromotionName.setText("Khuyến mãi mùa hè");

        lblPromotion.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        lblPromotion.setForeground(new java.awt.Color(0, 0, 0));
        lblPromotion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPromotion.setText("100.000d");

        lbl16.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl16.setForeground(new java.awt.Color(91, 91, 91));
        lbl16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl16.setText("Đặt cọc 30% tiền phòng");

        lblDeposit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDeposit.setForeground(new java.awt.Color(251, 128, 5));
        lblDeposit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeposit.setText("0");

        lbl15.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl15.setForeground(new java.awt.Color(91, 91, 91));
        lbl15.setText("Tổng tiền:");

        lblTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(0, 153, 51));
        lblTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalPrice.setText("0");

        lbl19.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl19.setForeground(new java.awt.Color(91, 91, 91));
        lbl19.setText("Tổng thành tiền:");

        lblTotalPricePayment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalPricePayment.setForeground(new java.awt.Color(0, 153, 51));
        lblTotalPricePayment.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalPricePayment.setText("0");

        btnCash.setBackground(new java.awt.Color(13, 200, 7));
        btnCash.setForeground(new java.awt.Color(255, 255, 255));
        btnCash.setText("TIỀN MẶT");
        btnCash.setBorderRadius(5);
        btnCash.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashActionPerformed(evt);
            }
        });

        bntTranfer.setBackground(new java.awt.Color(13, 200, 7));
        bntTranfer.setForeground(new java.awt.Color(255, 255, 255));
        bntTranfer.setText("CHUYỂN KHOẢN");
        bntTranfer.setBorderRadius(5);
        bntTranfer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntTranfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTranferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl31, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
                        .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl932, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl19, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblTotalPricePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl16, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblPromotionName, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(81, 81, 81)
                                            .addComponent(lblPromotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(1, 1, 1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddSurcharge, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214)
                        .addComponent(btnCash, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntTranfer, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(pnl6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl932)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPromotionName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl16)
                    .addComponent(lblDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl15)
                    .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalPricePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl19))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSurcharge, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCash, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntTranfer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashActionPerformed
        double totalPayment = Constants.parseVND(lblTotalPricePayment.getText());
        var modal = new CashPaymentModal(totalPayment);

        GlassPanePopup.showPopup(modal);

        modal.getBtnComplete().addActionListener(e -> {
            if (modal.getMoneyGiven() < totalPayment) {
                CustomDialog.showMessage(null,
                        "Khách đưa chưa đủ tiền!",
                        "Thông báo", CustomDialog.MessageType.WARNING, 300,200);
                return;
            }
            double change = modal.getMoneyGiven() - totalPayment;
            CustomDialog.showMessage(null,
                    "Thanh toán thành công! Tiền thừa: " + Constants.VND_FORMAT.format(change),
                    "Thông báo", CustomDialog.MessageType.SUCCESS, 500,200);

            currentOrder.setPromotion(promotion);
            currentOrder.setPaymentType(PaymentType.CASH);
            currentOrder.setTotalAmount(BigDecimal.valueOf(Constants.parseVND(lblTotalPricePayment.getText())));
            saveOrder();
            GlassPanePopup.closePopupAll();
        });
    }//GEN-LAST:event_btnCashActionPerformed

    private void saveOrder() {
         saveSurchargesByOrderId(currentOrder.getOrderId());
        orderService.updateOrderStatusToPaid(currentOrder);
        resetPanel();

    }

    private void resetPanel() {
        lblTotalPrice.setText("");
        lblTotalPricePayment.setText("");
        lblDeposit.setText("");
        lblPromotionName.setText("");
        lblPromotion.setText("");
        DefaultTableModel modelSurcharge = (DefaultTableModel) tblSurcharge.getModel();
        modelSurcharge.setRowCount(0);
        DefaultTableModel modelAmenity = (DefaultTableModel) tblAmenity.getModel();
        modelAmenity.setRowCount(0);

        lblFullName.setText("");
        lblPhone.setText("");
        lblEmail.setText("");
        lblCitizenid.setText("");
        lblDob.setText("");
        lblGender.setText("");

        lblCheckIn.setText("");
        lblCheckOut.setText("");
        lblTotalRoom.setText("");
        currentOrder = null;
        promotion = null;





    }

    private void saveSurchargesByOrderId(Long orderId) {
        DefaultTableModel model = (DefaultTableModel) tblSurcharge.getModel();

        List<SurchargeDetail> surchargesToSave = new ArrayList<>();

        for (int i = 0; i < model.getRowCount(); i++) {
            SurchargeDTO surchargeDTO = (SurchargeDTO) model.getValueAt(i, 1);
            SurchargeDetail surchargeDetail = new SurchargeDetail();
            surchargeDetail.setSurcharge(new Surcharge(surchargeDTO.getSurchargeId()));
            surchargeDetail.setQuantity(surchargeDTO.getQuantity());
            surchargesToSave.add(surchargeDetail);
        }

        surchargeDetailService.saveWithOrderId(orderId, surchargesToSave);

    }

    private void bntTranferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTranferActionPerformed
        PaymentService paymentService = new PaymentService();
        currentOrder.setPromotion(promotion);
        currentOrder.setPaymentType(PaymentType.E_WALLET);
        currentOrder.setTotalAmount(BigDecimal.valueOf(Constants.parseVND(lblTotalPricePayment.getText())));
        try {
            String response = paymentService.createPayment(currentOrder);
            String payUrl = paymentService.extractJsonValue(response, "payUrl");
            String orderId = paymentService.extractJsonValue(response, "orderId");
            var modal = new TransferPaymentModal();
            if (payUrl != null && !payUrl.isEmpty()) {
                modal.getLblQrCode().setIcon(new ImageIcon(paymentService.generateQRCodeImage(payUrl, 200, 200)));
            } else {
                CustomDialog.showMessage(null, "Hệ thống đang gặp sự cố khi tạo QR code vui lòng thử lại sau!", "Thông báo lỗi", CustomDialog.MessageType.ERROR,380,200);
            }

            modal.getLblTotaPrice().setText("Tổng tiền: " + currentOrder.getTotalAmount().longValue() + " VND");
            JFrame frame = new JFrame("Thanh toán MoMo QR");
            frame.setSize(300, 300);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setLayout(new BorderLayout());
            frame.setBackground(Color.WHITE);
            JPanel pnlMain = new JPanel();
            pnlMain.setBackground(Color.WHITE);
            pnlMain.setLayout(new BorderLayout());
            JLabel lblImage = new JLabel("", new ImageIcon(paymentService.generateQRCodeImage(payUrl, 250, 250)), SwingConstants.CENTER);
            JLabel lblPrice = new JLabel("Tổng tiền: " + currentOrder.getTotalAmount().longValue() + "VND", SwingConstants.CENTER);
            lblPrice.setFont(new Font("Segoe UI", Font.BOLD, 16));

            pnlMain.add(lblImage, BorderLayout.CENTER);
            pnlMain.add(lblPrice, BorderLayout.SOUTH);
            frame.add(pnlMain, BorderLayout.CENTER);
            frame.setVisible(true);

            GlassPanePopup.showPopup(modal);

            modal.getBtnCheck().addActionListener(e ->
            {
                try {
                    if (orderId == null) {
                        JOptionPane.showMessageDialog(null, "Chưa có đơn hàng nào!");
                        return;
                    }
                    String responseCheck = paymentService.queryPayment(orderId);
                    String responseCodeCheck = paymentService.extractJsonValue(responseCheck, "resultCode");
                    String orderIdCheck = paymentService.extractJsonValue(responseCheck, "orderId");
                    if ("0".equals(responseCodeCheck)) {
                        CustomDialog.showMessage(null, "Thanh toán thành công cho đơn hàng: " + orderIdCheck, "Thông báo", CustomDialog.MessageType.SUCCESS,380,200);
                        GlassPanePopup.closePopupAll();
                        frame.dispose();
                        saveOrder();
                    } else {
                        CustomDialog.showMessage(null, "Đơn hàng: " + orderIdCheck + " chưa được thanh toán. Vui lòng kiểm tra lại!", "Thông báo", CustomDialog.MessageType.WARNING,500,200);
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Lỗi: " + ex.getMessage());
                }
            });

        } catch (Exception e) {
            CustomDialog.showMessage(null, "Hệ thống đang gặp sự cố, vui lòng thử lại sau!", "Thông báo lỗi", CustomDialog.MessageType.ERROR,380,200);
        }
    }//GEN-LAST:event_bntTranferActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnPrevActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnCompleteActionPerformed

    private void btnAddSurchargeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddSurchargeActionPerformed
        // Create dialog instead of GlassPanePopup for better mouse event handling
        JDialog dialog = new JDialog((java.awt.Frame) SwingUtilities.getWindowAncestor(this),
                "Quản lý phụ phí", true);

        SurchargeManagementPanel surchargeManagementPanel = setupSurcharge(dialog);

        // Add action listener BEFORE showing dialog (modal blocks execution)
        surchargeManagementPanel.getSaveButton().addActionListener(e -> {
            System.out.println("Saving surcharges...");
            List<SurchargeDTO> selectedSurcharges = surchargeManagementPanel.getSelectedTableData();
            updateSurchargeTable(selectedSurcharges);
            saveSurcharges(selectedSurcharges.size());
            recalculateTotalAndPromotion(); // Recalculate total and apply promotion
            dialog.dispose();
        });

        dialog.setSize(1200, 800);
        dialog.setLocationRelativeTo(this);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        // Make dialog resizable
        dialog.setResizable(true);
        dialog.setMinimumSize(new Dimension(800, 600));

        // Show dialog (modal - will wait until closed)
        dialog.setVisible(true);

    }// GEN-LAST:event_btnAddSurchargeActionPerformed

    private void saveSurcharges(int size) {
        CustomDialog.showMessage(this,
                "Đã lưu " + size + " phụ phí vào đơn hàng.",
                "Lưu thành công",
                CustomDialog.MessageType.SUCCESS,
                400, 200);
    }

    private SurchargeManagementPanel setupSurcharge(JDialog dialog) {
        SurchargeManagementPanel surchargeManagementPanel = new SurchargeManagementPanel();
        var availableSurcharges = surchargeService.getAllSurcharges();

        var selectedSurcharges = new ArrayList<SurchargeDTO>();

        // Read real data from tblSurcharge
        // Columns: "STT", "Tên phụ phí", "Giá", "Số lượng", "Tổng tiền"
        DefaultTableModel model = (DefaultTableModel) tblSurcharge.getModel();

        if (model.getRowCount() > 0) {
            for (int i = 0; i < model.getRowCount(); i++) {
                SurchargeDTO surchargeDTO = (SurchargeDTO) model.getValueAt(i, 1);
                selectedSurcharges.add(surchargeDTO);
            }
        }

        surchargeManagementPanel.loadData(availableSurcharges, selectedSurcharges);

        // Add panel to dialog
        dialog.add(surchargeManagementPanel);
        return surchargeManagementPanel;
    }

    /**
     * Update surcharge table with selected surcharges from management panel
     */
    private void updateSurchargeTable(List<SurchargeDTO> surcharges) {
        DefaultTableModel model = (DefaultTableModel) tblSurcharge.getModel();
        model.setRowCount(0);

        int index = 1;
        BigDecimal total = BigDecimal.ZERO;

        for (SurchargeDTO surcharge : surcharges) {
            BigDecimal itemTotal = surcharge.getPrice().multiply(new BigDecimal(surcharge.getQuantity()));

            Object[] row = new Object[] {
                    index++, // Store ID in STT column for later retrieval
                    surcharge,
                    surcharge.getPrice(), // Store as BigDecimal, will be formatted by renderer
                    surcharge.getQuantity(),
                    itemTotal
            };

            total = total.add(itemTotal);
            model.addRow(row);
        }
        lblTotalSurcharge.setText(Constants.VND_FORMAT.format(total));

    }

    /**
     * Recalculate total price and update promotion based on current totals
     * Call this method whenever room/amenity/surcharge prices change
     */
    private void recalculateTotalAndPromotion() {
        // Calculate subtotal (before promotion and deposit)
        double totalRoom = Constants.parseVND(lblTotalRoom.getText());
        double totalAmenity = Constants.parseVND(lblTotalAmenity.getText());
        double totalSurcharge = Constants.parseVND(lblTotalSurcharge.getText());

        BigDecimal subtotal = BigDecimal.valueOf(totalRoom)
                .add(BigDecimal.valueOf(totalAmenity))
                .add(BigDecimal.valueOf(totalSurcharge));

        // Set lblTotalPrice to subtotal (before promotion and deposit)
        lblTotalPrice.setText(Constants.VND_FORMAT.format(subtotal));

        // Get and apply promotion based on subtotal
        setPromotion(subtotal);

        // Calculate final total (subtotal - promotion - deposit)
        double promotionDiscount = Constants.parseVND(lblPromotion.getText());
        double deposit = Constants.parseVND(lblDeposit.getText());

        double finalTotal = subtotal.doubleValue() - promotionDiscount - deposit;

        // Set lblTotalPricePayment to final amount (after promotion and deposit)
        lblTotalPricePayment.setText(Constants.VND_FORMAT.format(finalTotal));
    }

    @Deprecated
    private void updateLblTotalPrice() {
        // Deprecated: Use recalculateTotalAndPromotion() instead
        recalculateTotalAndPromotion();
    }

    public void setAmenity(List<AmenityDTO> selectedAmenities) {
        DefaultTableModel model = (DefaultTableModel) tblAmenity.getModel();
        model.setRowCount(0);
        int index = 1;
        BigDecimal total = BigDecimal.ZERO;
        for (AmenityDTO amenity : selectedAmenities) {
            Object[] row = new Object[] {
                    index++,
                    amenity.getName(),
                    Constants.VND_FORMAT.format(amenity.getPrice()),
                    amenity.getQuantity()
            };
            total = total.add(BigDecimal.valueOf(amenity.getPrice() * amenity.getQuantity()));
            model.addRow(row);
        }
        lblTotalAmenity.setText(Constants.VND_FORMAT.format(total));
        recalculateTotalAndPromotion(); // Recalculate when amenity changes
    }

    public void setupCustomer(Customer customer) {
        lblFullName.setText(customer.getFullName());
        lblPhone.setText(customer.getPhone());
        lblEmail.setText(customer.getEmail() != null ? customer.getEmail() : "N/A");
        lblCitizenid.setText(customer.getCitizenId());
        lblDob.setText(customer.getDateOfBirth().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        lblGender.setText(customer.isGender() ? "Nữ" : "Nam");
    }

    public void setInfoBooking(
            String checkIn,
            String checkOut,
            String bookingType,
            List<RoomSelection> selectedRoom,
            BigDecimal deposit,
            BigDecimal totalPrice) {

        lblCheckOut.setText(checkOut);
        lblBookingType.setText(bookingType);
        lblCheckIn.setText(checkIn);
        System.out.println("Deposit: " + deposit);
        lblDeposit.setText(Constants.VND_FORMAT.format(deposit));
        Map<String, List<RoomSelection>> map = selectedRoom.stream()
                .collect(Collectors.groupingBy(RoomSelection::getRoomType));

        for (Map.Entry<String, List<RoomSelection>> entry : map.entrySet()) {
            String roomTypeKey = entry.getKey();
            var listRoom = entry.getValue();
            String valueNew = listRoom.stream()
                    .map(RoomSelection::getNumber)
                    .collect(Collectors.joining(", "));
            if (roomTypeKey.equals("SINGLE")) {
                lblSingleRooms.setText(valueNew);
            } else if (roomTypeKey.equals("DOUBLE")) {
                lblDoubleRooms.setText(valueNew);
            }
        }
        lblTotalPrice.setText(Constants.VND_FORMAT.format(totalPrice));
        lblTotalRoom.setText(Constants.VND_FORMAT.format(totalPrice));
    }
    

    public void setOrder(Long orderId, OrderService orderService, OrderDetailService orderDetailService,
            SurchargeDetailService surchargeDetailService) {
        this.orderService = orderService;
        Order order = orderService.getOrderById(orderId);
        this.currentOrder = order;
        String checkInStr = order.getBookings().get(0).getCheckInDate()
                .format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"));
        String checkOutStr = order.getBookings().get(0).getCheckOutDate()
                .format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"));

        String bookingTypeStr = order.getBookings().get(0).getBookingType().getDisplayName();

        List<RoomSelection> selectedRooms = order.getBookings().stream()
                .map(b -> new RoomSelection(
                        b.getRoom().getRoomId(),
                        b.getRoom().getRoomNumber(),
                        b.getRoom().getRoomType().getRoomTypeId()))
                .toList();

        setInfoBooking(
                checkInStr,
                checkOutStr,
                bookingTypeStr,
                selectedRooms,
                order.getDeposit(),
                order.getTotalAmount());
        setupCustomer(order.getCustomer());

        List<AmenityDTO> amenityDTOS = orderDetailService.getOrderDetailsByOrderId(orderId).stream()
                .filter(od -> od.getAmenity() != null)
                .map(od -> {
                    Amenity amenity = od.getAmenity();
                    AmenityDTO dto = new AmenityDTO();
                    dto.setId(amenity.getAmenityId());
                    dto.setName(amenity.getNameAmenity());
                    dto.setPrice(amenity.getPrice().doubleValue());
                    dto.setQuantity(od.getQuantity());
                    return dto;
                })
                .toList();
        setAmenity(amenityDTOS);
        List<SurchargeDTO> surchargeDTOS = surchargeDetailService.getSurchargeDetailsByOrderId(orderId).stream()
                .map(e -> {
                    Surcharge surcharge = e.getSurcharge();
                    SurchargeDTO dto = new SurchargeDTO();
                    dto.setSurchargeId(surcharge.getSurchargeId());
                    dto.setName(surcharge.getName());
                    dto.setPrice(surcharge.getPrice());
                    dto.setQuantity(e.getQuantity());
                    return dto;
                }).toList();
        setSurcharge(surchargeDTOS);

        setPromotion(order.getTotalAmount());

    }

    private void setPromotion(BigDecimal totalAmount) {
        PromotionService promotionService = new PromotionService();
        promotion = promotionService.getActivePromotion(totalAmount);
        if (promotion != null) {
            lblPromotionName.setText(promotion.getPromotionName());
            // Calculate discount amount based on percentage
            BigDecimal discountPercent = new BigDecimal(promotion.getDiscountPercent().toString());
            BigDecimal discountAmount = totalAmount.multiply(discountPercent)
                    .divide(BigDecimal.valueOf(100));
            lblPromotion.setText(Constants.VND_FORMAT.format(discountAmount));
        } else {
            lblPromotionName.setText("Không có khuyến mãi");
            lblPromotion.setText(Constants.VND_FORMAT.format(0));
        }
    }

    private void setSurcharge(List<SurchargeDTO> surchargeDTOS) {
        tblSurcharge.clearSelection();
        updateSurchargeTable(surchargeDTOS);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.Button bntTranfer;
    private iuh.fit.se.group1.ui.component.custom.Button btnAddSurcharge;
    private iuh.fit.se.group1.ui.component.custom.Button btnCash;
    private iuh.fit.se.group1.ui.component.custom.Button btnPrev;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lbl932;
    private javax.swing.JLabel lblBookingType;
    private javax.swing.JLabel lblCheckIn;
    private javax.swing.JLabel lblCheckOut;
    private javax.swing.JLabel lblCitizenid;
    private javax.swing.JLabel lblDeposit;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblDoubleRooms;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPromotion;
    private javax.swing.JLabel lblPromotionName;
    private javax.swing.JLabel lblSingleRooms;
    private javax.swing.JLabel lblTotalAmenity;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblTotalPricePayment;
    private javax.swing.JLabel lblTotalRoom;
    private javax.swing.JLabel lblTotalSurcharge;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl31;
    private javax.swing.JPanel pnl4;
    private javax.swing.JPanel pnl5;
    private javax.swing.JPanel pnl6;
    private javax.swing.JPanel pnl9;
    private javax.swing.JScrollPane scr;
    private javax.swing.JScrollPane scr1;
    private javax.swing.JSeparator spn1;
    private javax.swing.JSeparator spn2;
    private javax.swing.JSeparator spn4;
    private javax.swing.JSeparator spn6;
    private javax.swing.JTable tblAmenity;
    private javax.swing.JTable tblSurcharge;
    // End of variables declaration//GEN-END:variables
}
