/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.dashboard;


import javax.swing.*;
import java.awt.*;

/**
 * @author THIS PC
 */
public class CardReport extends javax.swing.JPanel {

    private Color borderColor = new Color(41, 121, 255);

    /**
     * Creates new form CardReport
     */
    public CardReport() {
        initComponents();
        setOpaque(false);
    }

    public void setTitle(String title) {
        lblTitle.setText(title);
    }


    public void setBorderColor (Color borderColor) {
        this.borderColor = borderColor;
        repaint();
    }
    /**
     * Set value for label value
     * @param value
     */
    public void setLblValue(String value) {
        lblValue.setText(value);
    }

    /**
     * Set icon for label rate
     * @param icon
     */
    public void setLblIconRate(Icon icon) {
        lblIconRate.setText("");
        lblIconRate.setIcon(icon);
    }

    /**
     * Set percentage for circular progress and label room count
     * @param room current room
     * @param totalRoom total room
     */
    public void setPercentage(int room, int totalRoom) {
        int percentage = (int) ((room * 1.0 / totalRoom) * 100);
        String value = room + "/" + totalRoom + " phòng";
        lblRoomCount.setText(value);
        circularProgress1.setProgress(percentage);
    }

    public void setColorCircularProgress(Color color) {
        circularProgress1.setProgressColor(color);
    }

    /**
     * Set message for label room count and hide circular progress
     * @param message
     */
    public void setMessage(String message){
        circularProgress1.setVisible(false);
        lblRoomCount.setText(message);

    } 




    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int width = getWidth();
        int height = getHeight();
        int arc = 16; // bo góc panel
        int borderHeight = 3; // border-bottom mảnh hơn
        int shadowOffset = 4;
        int shadowBlur = 6;

        Color shadowColor = new Color(0, 0, 0, 30);

        // ===== Bóng đổ =====
        g2.setPaint(new GradientPaint(0, height - shadowBlur, shadowColor,
                0, height, new Color(0, 0, 0, 0)));
        g2.fillRoundRect(0, shadowOffset, width, height - shadowOffset, arc, arc);

        // ===== Nền trắng =====
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, width, height - borderHeight, arc, arc);

        // ===== Border-bottom bo chỉ 2 góc dưới =====
        g2.setColor(borderColor);
        java.awt.geom.Path2D.Float path = new java.awt.geom.Path2D.Float();
        path.moveTo(0, height - borderHeight - arc / 2);
        path.lineTo(0, height - arc / 3);
        path.quadTo(0, height, arc / 2, height);
        path.lineTo(width - arc / 2, height);
        path.quadTo(width, height, width, height - arc / 3);
        path.lineTo(width, height - borderHeight - arc / 2);
        path.closePath();
        g2.fill(path);

        g2.dispose();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblIconRate = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        circularProgress1 = new iuh.fit.se.group1.ui.component.custom.CircularProgress();
        lblRoomCount = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("TỶ LỆ ĐẶT PHÒNG");

        lblIconRate.setText("X");

        lblValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblValue.setForeground(new java.awt.Color(199, 19, 7));
        lblValue.setText("15%");

        javax.swing.GroupLayout circularProgress1Layout = new javax.swing.GroupLayout(circularProgress1);
        circularProgress1.setLayout(circularProgress1Layout);
        circularProgress1Layout.setHorizontalGroup(
            circularProgress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        circularProgress1Layout.setVerticalGroup(
            circularProgress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        lblRoomCount.setForeground(new java.awt.Color(131, 131, 131));
        lblRoomCount.setText("20/30 phòng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRoomCount, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIconRate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(circularProgress1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIconRate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(circularProgress1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRoomCount)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.CircularProgress circularProgress1;
    private javax.swing.JLabel lblIconRate;
    private javax.swing.JLabel lblRoomCount;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables
}
