/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.menu;

import iuh.fit.se.group1.ui.component.custom.Button;
import iuh.fit.se.group1.util.Constants;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.border.EmptyBorder;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author THIS PC
 */
public class ProfileButton extends javax.swing.JPanel {

    /**
     * Creates new form ProfileButton
     */
    public ProfileButton() {
        initComponents();
        lblRoleName.setForeground(Constants.FOREGROUND_COLOR_MENU);
        lblFullName.setForeground(Constants.FOREGROUND_COLOR_MENU);
        btnSignOut.setText("");
        btnSignOut.setIcon(FontIcon.of(FontAwesomeSolid.SIGN_OUT_ALT, 18, Constants.FOREGROUND_COLOR_MENU));
        btnSignOut.setBackground(Constants.BACKGROUND_COLOR_MENU);
        btnSignOut.setBorder(new EmptyBorder(10,0,0,0));
        btnSignOut.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    
    public Button getBtnSignOut() {
        return btnSignOut;
    }

    public void setBtnSignOut(Button btnSignOut) {
        this.btnSignOut = btnSignOut;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRoleName = new javax.swing.JLabel();
        lblAvartar = new iuh.fit.se.group1.ui.component.custom.CircleLabel();
        lblFullName = new javax.swing.JLabel();
        btnSignOut = new iuh.fit.se.group1.ui.component.custom.Button();

        setBackground(new java.awt.Color(255, 255, 255));

        lblRoleName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRoleName.setText("Nhân viên quản lí");

        lblAvartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avttest.jpg"))); // NOI18N
        lblAvartar.setText("");

        lblFullName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFullName.setText("Nguyễn Phước Thịnh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblAvartar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnSignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvartar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblFullName))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.Button btnSignOut;
    private iuh.fit.se.group1.ui.component.custom.CircleLabel lblAvartar;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblRoleName;
    // End of variables declaration//GEN-END:variables
}
