/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.version;

import iuh.fit.se.group1.ui.component.custom.Button;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URI;

/**
 * @author VienThieu
 */
public class CheckForVersionPanel extends javax.swing.JPanel {

    public CheckForVersionPanel() {
        initComponents();
        lblInfo4.setText("<html>Liên hệ: <a href='' style='color:#3291FF;'>daotienhotelgroup1@gmail.com</a> | 033 8687106</html>");

        lblInfo4.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().mail(new URI("mailto:daotienhotelgroup1@gmail.com"));
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
        lblInfo4.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblInfo4.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
//                JOptionPane.showMessageDialog(null, "Bạn vừa click vào support@daotienhms.vn");
            }
        });

//        ImageIcon icon = new ImageIcon("src/main/resources/images/z7133187287314_6019d3504836aa41c92dddc9551ee796-removebg-preview.png");
//        // Đọc ảnh gốc
//        BufferedImage original = null;
//        try {
//            original = ImageIO.read(new File("src/main/resources/images/z7133187287314_6019d3504836aa41c92dddc9551ee796-removebg-preview.png"));
//        } catch (IOException e) {
//            throw new RuntimeException(e);
//        }

//        // Resize với chất lượng cao
//        int width = 64;
//        int height = 64;
//        BufferedImage resized = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
//
//        Graphics2D g2 = resized.createGraphics();
//        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
//        g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
//        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//        g2.drawImage(original, 0, 0, width, height, null);
//        g2.dispose();
//        lblLogoPage.setIcon(new ImageIcon(resized));

        BufferedImage original = null;
        try {
            original = ImageIO.read(getClass().getResourceAsStream("/images/z7133187287314_6019d3504836aa41c92dddc9551ee796-removebg-preview.png"));
        } catch (IOException e) {
            throw new RuntimeException("Không thể đọc ảnh resource!", e);
        }

        int width = 64;
        int height = 64;
        BufferedImage resized = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);

        Graphics2D g2 = resized.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
        g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.drawImage(original, 0, 0, width, height, null);
        g2.dispose();
        lblLogoPage.setIcon(new ImageIcon(resized));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogoPage = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblTitleHMS = new javax.swing.JLabel();
        lblInfo1 = new javax.swing.JLabel();
        lblInfo2 = new javax.swing.JLabel();
        lblInfo3 = new javax.swing.JLabel();
        lblInfo4 = new javax.swing.JLabel();
        lblInfo5 = new javax.swing.JLabel();
        btnCheckForUpdate = new iuh.fit.se.group1.ui.component.custom.Button();
        btnClose = new iuh.fit.se.group1.ui.component.custom.Button();

        setBackground(new java.awt.Color(255, 255, 255));

        lblLogoPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo64.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Hệ thống quản lí khách sạn Đào Tiên");

        lblTitleHMS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitleHMS.setText("Hệ thống quản lí khách sạn đào tiên (Đào Tiên)");

        lblInfo1.setText("Phiên bản: 1.0.0, ra mắt 01/01/2026.");

        lblInfo2.setText("Yêu cầu: Java 21+, RAM 8GB+, SQL Server 21.");

        lblInfo3.setText("Tính năng chính: Đặt phòng, quản lí hệ thống thích hợp, tích hợp Momo thanh toán. Changelog mới: ");

        lblInfo4.setText("Liên hệ: daotienhotelgroup1@gmail.com | 0338687106");

        lblInfo5.setBackground(new java.awt.Color(255, 255, 255));
        lblInfo5.setText("Powered by open-source. © 2025 Đào Tiên Software.");

        btnCheckForUpdate.setBackground(new java.awt.Color(50, 145, 255));
        btnCheckForUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckForUpdate.setText("Kiểm tra cập nhật");
        btnCheckForUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCheckForUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckForUpdateActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(150, 150, 150));
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Đóng");
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnCheckForUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblLogoPage)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lblInfo1)
                                                        .addComponent(lblTitleHMS)
                                                        .addComponent(lblInfo2)
                                                        .addComponent(lblInfo4)
                                                        .addComponent(lblInfo5)
                                                        .addComponent(lblInfo3)))
                                        .addComponent(lblTitle))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblTitle)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(lblTitleHMS)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblInfo1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblInfo2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(lblLogoPage)))
                                .addGap(18, 18, 18)
                                .addComponent(lblInfo3)
                                .addGap(18, 18, 18)
                                .addComponent(lblInfo4)
                                .addGap(18, 18, 18)
                                .addComponent(lblInfo5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCheckForUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckForUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckForUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckForUpdateActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    public Button getBtnCheckForUpdate() {
        return btnCheckForUpdate;
    }

    public void setBtnCheckForUpdate(Button btnCheckForUpdate) {
        this.btnCheckForUpdate = btnCheckForUpdate;
    }

    public Button getBtnClose() {
        return btnClose;
    }

    public void setBtnClose(Button btnClose) {
        this.btnClose = btnClose;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.Button btnCheckForUpdate;
    private iuh.fit.se.group1.ui.component.custom.Button btnClose;
    private javax.swing.JLabel lblInfo1;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblInfo3;
    private javax.swing.JLabel lblInfo4;
    private javax.swing.JLabel lblInfo5;
    private javax.swing.JLabel lblLogoPage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleHMS;
    // End of variables declaration//GEN-END:variables
}
