/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.chart;

import iuh.fit.se.group1.ui.component.booking2.CalendarUI;
import iuh.fit.se.group1.ui.component.custom.Button;
import iuh.fit.se.group1.ui.component.custom.TextField;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author THIS PC
 */
public class HeaderChart extends javax.swing.JPanel {

    public TextField getTxtFromDate() {
        return txtFromDate;
    }

    public void setTxtFromDate(TextField txtFromDate) {
        this.txtFromDate = txtFromDate;
    }

    public TextField getTxtToDate() {
        return txtToDate;
    }

    public void setTxtToDate(TextField txtToDate) {
        this.txtToDate = txtToDate;
    }

    /**
     * Creates new form HeaderChart
     */
    public HeaderChart() {
        initComponents();
        txtFromDate.setEditable(false);
        txtToDate.setEditable(false);
        txtFromDate.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        txtToDate.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));

        txtFromDate.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalendarUI.showCalendar(txtFromDate, null, null, false);
            }
        });

        txtToDate.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalendarUI.showCalendar(txtToDate, null, null, false);
            }
        });
    }

    public Button getBtnView() {
        return btnView;
    }

    public void setBtnView(Button btnView) {
        this.btnView = btnView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnView = new iuh.fit.se.group1.ui.component.custom.Button();
        txtFromDate = new iuh.fit.se.group1.ui.component.custom.TextField();
        txtToDate = new iuh.fit.se.group1.ui.component.custom.TextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(108, 165, 200));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 246, 246));
        jLabel1.setText("Quản lí thống kê");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText(">Doanh thu");

        btnView.setBackground(new java.awt.Color(255, 108, 3));
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("Xem");
        btnView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtFromDate.setEditable(false);
        txtFromDate.setBackground(new java.awt.Color(108, 165, 200));
        txtFromDate.setForeground(new java.awt.Color(255, 255, 255));
        txtFromDate.setText("textField1");
        txtFromDate.setBorderColor(java.awt.Color.white);
        txtFromDate.setBorderRadius(5);
        txtFromDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtToDate.setBackground(new java.awt.Color(108, 165, 200));
        txtToDate.setForeground(new java.awt.Color(255, 255, 255));
        txtToDate.setText("textField1");
        txtToDate.setBorderColor(java.awt.Color.white);
        txtToDate.setBorderRadius(5);
        txtToDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel3.setText("đến");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(txtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.Button btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private iuh.fit.se.group1.ui.component.custom.TextField txtFromDate;
    private iuh.fit.se.group1.ui.component.custom.TextField txtToDate;
    // End of variables declaration//GEN-END:variables
}
