/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.layout;

import iuh.fit.se.group1.enums.TimeType;

/**
 *
 * @author THIS PC
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        // todo: hard code card
        fetchData();
        addActionTimeType();


    }

    private void addActionTimeType() {
        headerDashboard1.getBtnToday().addActionListener(e -> {
            headerDashboard1.setActiveButton(TimeType.TODAY);
//            System.out.println(lineChartPanel1.getWidth() + " " + lineChartPanel1.getHeight());
            // TODO: Update chart and data for Today
        });

        headerDashboard1.getBtn7Days().addActionListener(e -> {
            headerDashboard1.setActiveButton(TimeType.DAYS_7);
            // TODO: Update chart and data for 7 Days
        });

        headerDashboard1.getBtn30Days().addActionListener(e -> {
            headerDashboard1.setActiveButton(TimeType.DAYS_30);
            // TODO: Update chart and data for 30 Days
        });

        headerDashboard1.getBtn90Days().addActionListener(e -> {
            headerDashboard1.setActiveButton(TimeType.DAYS_90);
            // TODO: Update chart and data for 90 Days
        });

    }

    private void fetchData() {
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlListCard1 = new iuh.fit.se.group1.ui.component.dashboard.PnlListCard();
        headerDashboard1 = new iuh.fit.se.group1.ui.component.dashboard.HeaderDashboard();
        pnlFooter = new javax.swing.JPanel();
        panelWarning1 = new iuh.fit.se.group1.ui.component.dashboard.PanelWarning();
        cardLiquid1 = new iuh.fit.se.group1.ui.component.chart.CardLiquid();
        cardLiquid2 = new iuh.fit.se.group1.ui.component.chart.CardLiquid();
        revenueChart1 = new iuh.fit.se.group1.ui.component.dashboard.RevenueChart();
        lineChartPanel1 = new iuh.fit.se.group1.ui.component.dashboard.LineChartPanel();

        setBackground(new java.awt.Color(241, 241, 241));
        setForeground(new java.awt.Color(241, 241, 241));

        pnlFooter.setBackground(new java.awt.Color(241, 241, 241));

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panelWarning1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(cardLiquid1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(cardLiquid2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardLiquid2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardLiquid1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWarning1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlListCard1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerDashboard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(revenueChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(lineChartPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlListCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lineChartPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(revenueChart1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.chart.CardLiquid cardLiquid1;
    private iuh.fit.se.group1.ui.component.chart.CardLiquid cardLiquid2;
    private iuh.fit.se.group1.ui.component.dashboard.HeaderDashboard headerDashboard1;
    private iuh.fit.se.group1.ui.component.dashboard.LineChartPanel lineChartPanel1;
    private iuh.fit.se.group1.ui.component.dashboard.PanelWarning panelWarning1;
    private javax.swing.JPanel pnlFooter;
    private iuh.fit.se.group1.ui.component.dashboard.PnlListCard pnlListCard1;
    private iuh.fit.se.group1.ui.component.dashboard.RevenueChart revenueChart1;
    // End of variables declaration//GEN-END:variables
}
