/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.layout;

import iuh.fit.se.group1.enums.TimeType;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.material.Material;
import org.kordamp.ikonli.swing.FontIcon;

import java.awt.*;

/**
 *
 * @author THIS PC
 */
public class DashboardEmployee extends javax.swing.JPanel {

    private static final Color ALMOST_OUT_OF_TIME = new Color(50, 145, 255);
    private static final Color NUMBER_CHECKIN = new Color(255, 108, 3);
    private static final Color NUMBER_CHECKOUT = new Color(239, 180, 46);
    private static final Color MONEY_OPEN_SHIFT = new Color(13,200, 7);
    /**
     * Creates new form DashboardEmployee
     */
    public DashboardEmployee() {
        initComponents();
        addActionTimeType();
        pnlListCard1.getRoomOccupancyRateCard().setLblIconRate(FontIcon.of(FontAwesomeSolid.CLOCK, 24, ALMOST_OUT_OF_TIME));
        pnlListCard1.getRoomOccupancyRateCard().setTitle("SỐ PHÒNG SẮP HẾT HẠN");
        pnlListCard1.getRoomOccupancyRateCard().setMessage("12/30 phòng");
        pnlListCard1.getRoomOccupancyRateCard().setLblValue("12 PHÒNG");

        pnlListCard1.getNumberCheckInCard().setLblIconRate(FontIcon.of(FontAwesomeSolid.MAP_MARKER_ALT, 24, NUMBER_CHECKIN));
        pnlListCard1.getNumberCheckInCard().setTitle("LƯỢT KHÁCH CHECKIN");
        pnlListCard1.getNumberCheckInCard().setMessage("Tắng 8% so với cùng kì");
        pnlListCard1.getNumberCheckInCard().setLblValue("72 LƯỢT");

        pnlListCard1.getRevenueCard().setLblIconRate(FontIcon.of(FontAwesomeSolid.KEY, 24, ALMOST_OUT_OF_TIME));
        pnlListCard1.getRevenueCard().setTitle("LƯỢT KHÁCH CHECKOUT");
        pnlListCard1.getRevenueCard().setMessage("20/30 phòng");
        pnlListCard1.getRevenueCard().setLblValue("12 LƯỢT");

        pnlListCard1.getBookingRateCard().setLblIconRate(FontIcon.of(FontAwesomeSolid.MONEY_CHECK, 24, ALMOST_OUT_OF_TIME));
        pnlListCard1.getBookingRateCard().setTitle("TIỀN KHI MỞ CA");
        pnlListCard1.getBookingRateCard().setMessage("đá");
        pnlListCard1.getBookingRateCard().getLblRoomCount().setForeground(Color.white);
        pnlListCard1.getBookingRateCard().setLblValue("200000000");
    }

    private void addActionTimeType() {
        headerDashboard.getBtnToday().addActionListener(e -> {
            headerDashboard.setActiveButton(TimeType.TODAY);
            // TODO: Update chart and data for Today
        });

        headerDashboard.getBtn7Days().addActionListener(e -> {
            headerDashboard.setActiveButton(TimeType.DAYS_7);
            // TODO: Update chart and data for 7 Days
        });

        headerDashboard.getBtn30Days().addActionListener(e -> {
            headerDashboard.setActiveButton(TimeType.DAYS_30);
            // TODO: Update chart and data for 30 Days
        });

        headerDashboard.getBtn90Days().addActionListener(e -> {
            headerDashboard.setActiveButton(TimeType.DAYS_90);
            // TODO: Update chart and data for 90 Days
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerDashboard = new iuh.fit.se.group1.ui.component.dashboard.HeaderDashboard();
        revenueChart = new iuh.fit.se.group1.ui.component.dashboard.RevenueChart();
        lineChartPanel = new iuh.fit.se.group1.ui.component.dashboard.LineChartPanel();
        cardNote = new iuh.fit.se.group1.ui.component.dashboard.CardNote();
        panelWarning = new iuh.fit.se.group1.ui.component.dashboard.PanelWarning();
        statusRoomCard = new iuh.fit.se.group1.ui.component.dashboard.StatusRoomCard();
        pnlListCard1 = new iuh.fit.se.group1.ui.component.dashboard.PnlListCard();

        setBackground(new java.awt.Color(241, 241, 241));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(revenueChart, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lineChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cardNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(statusRoomCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
            .addComponent(pnlListCard1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlListCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(revenueChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lineChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusRoomCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.dashboard.CardNote cardNote;
    private iuh.fit.se.group1.ui.component.dashboard.HeaderDashboard headerDashboard;
    private iuh.fit.se.group1.ui.component.dashboard.LineChartPanel lineChartPanel;
    private iuh.fit.se.group1.ui.component.dashboard.PanelWarning panelWarning;
    private iuh.fit.se.group1.ui.component.dashboard.PnlListCard pnlListCard1;
    private iuh.fit.se.group1.ui.component.dashboard.RevenueChart revenueChart;
    private iuh.fit.se.group1.ui.component.dashboard.StatusRoomCard statusRoomCard;
    // End of variables declaration//GEN-END:variables
}
