/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.layout;

import iuh.fit.se.group1.util.Constants;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author vietn
 */
public class HomePage extends javax.swing.JPanel {

    /**
     * Creates new form HomePage
     */
    private Image backgroundImage;
    public HomePage() {
        initComponents();
        setSize(Constants.WIDTH_FRAME, Constants.HEIGHT_FRAME);
        backgroundImage = new ImageIcon(getClass().getResource("/images/background.png")).getImage();
       setLayout(null);

// Cho phép Swing tính lại kích thước thật sau khi font render xong
SwingUtilities.invokeLater(() -> {
    // Lấy kích thước thật sau khi render
    lblTitle.setSize(lblTitle.getPreferredSize());
    lblXinChao.setSize(lblXinChao.getPreferredSize());
    centerLabels();
});

// Lắng nghe khi resize frame/panel để tự căn giữa lại
addComponentListener(new java.awt.event.ComponentAdapter() {
    @Override
    public void componentResized(java.awt.event.ComponentEvent e) {
        centerLabels();
    }
});
    }
    private void centerLabels() {
    int parentWidth = getWidth();
    int parentHeight = getHeight();

    int totalHeight = lblTitle.getHeight() + 10 + lblXinChao.getHeight();

    int startY = (parentHeight - totalHeight) / 2;

    int xTitle = (parentWidth - lblTitle.getWidth()) / 2;
    int xXinChao = (parentWidth - lblXinChao.getWidth()) / 2;

    lblTitle.setLocation(xTitle, startY);
    lblXinChao.setLocation(xXinChao, startY + lblTitle.getHeight() + 10);
}
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Vẽ hình nền full panel
        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblXinChao = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 153));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("HỆ THỐNG QUẢN LÝ");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblXinChao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblXinChao.setForeground(new java.awt.Color(255, 255, 255));
        lblXinChao.setText("Xin chào!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(739, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(451, 451, 451))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblXinChao)
                        .addGap(525, 525, 525))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(391, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblXinChao)
                .addGap(399, 399, 399))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblXinChao;
    // End of variables declaration//GEN-END:variables
}
