/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.layout;


import javax.swing.JLabel;


/**
 *
 * @author Windows
 */
public class Regulation extends javax.swing.JPanel {

    public JLabel getLblRegulation() {
        return lblRegulation;
    }

    public void setLblRegulation(JLabel lblRegulation) {
        this.lblRegulation = lblRegulation;
    }

    


    public Regulation() {
        initComponents();
        headerShift1.getLblTile().setText(
                "<html>"
                        + "<span style='font-size:20px;color:white;'>Quy Định - Đào Tiên Hotel</span><br>"
                        + "<span style='font-size:15px;color:white;'>Môn học: Phát triển Ứng dụng – Khoa CNTT, IUH</span><br>"
                        + "<span style='font-size:15px;color:white;'>GV hướng dẫn: Trần Thị Anh Thi | © 2025 Nhóm 1</span>"
                        + "</html>"
        );
        
        headerShift1.getLblSubTitle().setText("");
        
       getLblRegulation().setText(
    "<html>"
  + "<b>Giờ nhận phòng (Check-in)</b><br>"
  + "Đối với theo ngày: Khách được nhận phòng từ 14h. Nếu khách check-in trước 14h hệ thống tự động tính phụ thu 20.000đ/giờ.<br>"
  + "Đối với theo giờ: Nếu khách đến sau 22h nhưng chỉ ở 1–2 tiếng thì vẫn được tính theo gói qua đêm.<br>"
  + "Ràng buộc: không cho phép check-in trước 06h sáng của cùng ngày.<br><br>"

  + "<b>Giờ trả phòng (Check-out)</b><br>"
  + "Khách phải trả phòng trước 12h trưa.<br>"
  + "Nếu khách trả phòng sau 12h khách sạn tính phụ thu 30.000đ/giờ.<br>"
  + "Nếu khách trả phòng muộn không quá 30 phút thì không tính phí.<br>"
  + "Nếu thời gian trả phòng vượt quá 18h, hệ thống tự động tính thêm 1 ngày lưu trú.<br><br>"

  + "<b>Quy định về giấy tờ tùy thân</b><br>"
  + "Khách đi một mình hoặc theo nhóm đều phải xuất trình tối thiểu 1 giấy tờ tùy thân để nhân viên chụp lại thông tin."
  + "</html>"
);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerShift1 = new iuh.fit.se.group1.ui.component.HeaderShift();
        lblRegulation = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblRegulation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegulation.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerShift1, javax.swing.GroupLayout.DEFAULT_SIZE, 1155, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblRegulation, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerShift1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(lblRegulation, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.HeaderShift headerShift1;
    private javax.swing.JLabel lblRegulation;
    // End of variables declaration//GEN-END:variables
}
