/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.layout;

import iuh.fit.se.group1.enums.TimeType;
import iuh.fit.se.group1.service.OrderService;
import iuh.fit.se.group1.ui.component.booking2.CalendarUI;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 *
 * @author THIS PC
 */
public class RevenueStatistics extends javax.swing.JPanel {

    private OrderService orderService = new OrderService();

    /**
     * Creates new form RevenueStatistics
     */
    public RevenueStatistics() {
        initComponents();
        setActionButtonRange();

        headerChart1.getBtnView().addActionListener(e -> {
            String fromDate = headerChart1.getTxtFromDate().getText();
            String toDate = headerChart1.getTxtToDate().getText();

            LocalDate from = parseDate(fromDate);
            LocalDate to = parseDate(toDate);

            loadData(from, to);
        });
    }

    private void loadData(LocalDate from, LocalDate to) {
        // Lấy tổng doanh thu
        BigDecimal totalRevenue = orderService.getTotalRevenueBetweenDates(from, to);

        card1.setValue(totalRevenue);

//        // Calculate total revenue
//        double totalRevenue = revenueData.stream()
//                .mapToDouble(data -> ((Number) data[1]).doubleValue())
//                .sum();
//
//        card1.setValue(String.format("%.2f", totalRevenue));
    }

    public LocalDate parseDate(String date) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return LocalDate.parse(date, formatter);
    }



    private void setActionButtonRange() {
        rangeDateButton1.getBtn7Days().addActionListener(e -> {
            rangeDateButton1.setActiveButton(TimeType.DAYS_7);

            LocalDate to = LocalDate.now();
            LocalDate from = to.minusDays(7);
            headerChart1.getTxtFromDate().setText(from.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
            headerChart1.getTxtToDate().setText(to.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));

            loadData(from,to);

        });
        rangeDateButton1.getBtn30Days().addActionListener(e -> {
            rangeDateButton1.setActiveButton(TimeType.DAYS_30);

            LocalDate to = LocalDate.now();
            LocalDate from = to.minusDays(30);

            headerChart1.getTxtFromDate().setText(from.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
            headerChart1.getTxtToDate().setText(to.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));

            loadData(from,to);
        });
        rangeDateButton1.getBtn90Days().addActionListener(e -> {
            rangeDateButton1.setActiveButton(TimeType.DAYS_90);
            LocalDate to = LocalDate.now();
            LocalDate from = to.minusDays(90);
            headerChart1.getTxtFromDate().setText(from.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
            headerChart1.getTxtToDate().setText(to.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
            loadData(from,to);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        revenueColumnChart1 = new iuh.fit.se.group1.ui.component.chart.RevenueColumnChart();
        rangeDateButton1 = new iuh.fit.se.group1.ui.component.chart.RangeDateButton();
        card1 = new iuh.fit.se.group1.ui.component.chart.Card();
        headerChart1 = new iuh.fit.se.group1.ui.component.chart.HeaderChart();

        setBackground(new java.awt.Color(241, 241, 241));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(revenueColumnChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(rangeDateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addComponent(headerChart1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerChart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rangeDateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(revenueColumnChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.chart.Card card1;
    private iuh.fit.se.group1.ui.component.chart.HeaderChart headerChart1;
    private iuh.fit.se.group1.ui.component.chart.RangeDateButton rangeDateButton1;
    private iuh.fit.se.group1.ui.component.chart.RevenueColumnChart revenueColumnChart1;
    // End of variables declaration//GEN-END:variables
}
