/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.layout;

import iuh.fit.se.group1.ui.component.custom.Combobox;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * @author THIS PC
 */
public class StatisticsDetail extends javax.swing.JPanel {

    /**
     * Creates new form StatisticsDetail
     */
    public StatisticsDetail() {
        initComponents();
        headerCustom.getLblTitle().setText("Chi tiết thống kê");
        customTable();
    }

    private void customTable() {
        addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                tbl.getTbl().clearSelection();
            }
        });
        String cols[] = {"Mã hóa đơn", "Ngày đặt", "Ngày trả", "Doanh thu", "Loại phòng"};
        DefaultTableModel model = new DefaultTableModel(cols, 0);
        tbl.getTbl().setModel(model);

        var header = tbl.getTbl().getTableHeader();
        Combobox<String> cmbCheckInDate = new Combobox<>(new String[]{"Tất cả", "6h-12h", "12h-18h", "18h-0h", "0h-6h"});
        Combobox<String> cmbRevenue = new Combobox<>(new String[]{"Tất cả", "Tăng dần", "Giảm dần"});
        Combobox<String> cmbRoomType = new Combobox<>(new String[]{"Tất cả", "Phòng Đơn", "Phòng đôi"});

        var colModel = tbl.getTbl().getColumnModel();
        TableCellRenderer defaultRenderer = header.getDefaultRenderer();

        colModel.getColumn(1).setHeaderRenderer((tbl, value, isSelected, hasFocus, row, col) -> {
            Component comp = defaultRenderer.getTableCellRendererComponent(tbl, value, isSelected, hasFocus, row, col);
            if (comp instanceof JLabel lbl) {
                String text = "Ngày đặt                           \u25BC";
                lbl.setText(text);
                lbl.setHorizontalAlignment(SwingConstants.LEFT);
            }
            return comp;
        });

        colModel.getColumn(3).setHeaderRenderer((tbl, value, isSelected, hasFocus, row, col) -> {
            Component comp = defaultRenderer.getTableCellRendererComponent(tbl, value, isSelected, hasFocus, row, col);
            if (comp instanceof JLabel lbl) {
                String text = "Doanh thu                             \u25BC";
                lbl.setText(text);
                lbl.setHorizontalAlignment(SwingConstants.LEFT);
            }
            return comp;
        });

        colModel.getColumn(4).setHeaderRenderer((tbl, value, isSelected, hasFocus, row, col) -> {
            Component comp = defaultRenderer.getTableCellRendererComponent(tbl, value, isSelected, hasFocus, row, col);
            if (comp instanceof JLabel lbl) {
                String text = "Loại phòng                             \u25BC";
                lbl.setText(text);
                lbl.setHorizontalAlignment(SwingConstants.LEFT);
            }
            return comp;
        });

        header.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int col = header.columnAtPoint(e.getPoint());
                switch (col) {
                    case 1:
                        showCombo(cmbCheckInDate, col);
                        break;
                    case 3:
                        showCombo(cmbRevenue, col);
                        break;
                    case 4:
                        showCombo(cmbRoomType, col);
                        break;
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void showCombo(Combobox<String> combo, int col) {
        Rectangle rect = tbl.getTbl().getTableHeader().getHeaderRect(col);
        combo.setBounds(rect);
        combo.setVisible(true);
        tbl.getTbl().getTableHeader().add(combo);
        combo.showPopup();

        combo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent fe) {
                combo.setVisible(false);
                tbl.getTbl().getTableHeader().remove(combo);
            }
        });
    }

        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents () {

            headerCustom = new iuh.fit.se.group1.ui.component.HeaderCustom();
            rangeDateButton = new iuh.fit.se.group1.ui.component.chart.RangeDateButton();
            txtDateForm = new iuh.fit.se.group1.ui.component.custom.TextField();
            lblTo = new javax.swing.JLabel();
            txtDateTo = new iuh.fit.se.group1.ui.component.custom.TextField();
            btnView = new iuh.fit.se.group1.ui.component.custom.Button();
            tbl = new iuh.fit.se.group1.ui.component.table.Table();
            btnExportPDF = new iuh.fit.se.group1.ui.component.custom.Button();
            btnExportExcel = new iuh.fit.se.group1.ui.component.custom.Button();
            btnReset = new iuh.fit.se.group1.ui.component.custom.Button();

            setBackground(new java.awt.Color(241, 241, 241));

            txtDateForm.setText("textField1");
            txtDateForm.setBorderColor(java.awt.Color.black);
            txtDateForm.setBorderRadius(5);

            lblTo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            lblTo.setForeground(new java.awt.Color(0, 0, 0));
            lblTo.setText("đến");

            txtDateTo.setText("textField1");
            txtDateTo.setBorderColor(java.awt.Color.black);
            txtDateTo.setBorderRadius(5);

            btnView.setBackground(new java.awt.Color(255, 108, 3));
            btnView.setForeground(new java.awt.Color(255, 255, 255));
            btnView.setText("Xem");
            btnView.setBorderRadius(5);
            btnView.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

            btnExportPDF.setBackground(new java.awt.Color(255, 108, 3));
            btnExportPDF.setForeground(new java.awt.Color(255, 255, 255));
            btnExportPDF.setText("Xuất file FDF");
            btnExportPDF.setBorderRadius(5);
            btnExportPDF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

            btnExportExcel.setBackground(new java.awt.Color(255, 108, 3));
            btnExportExcel.setForeground(new java.awt.Color(255, 255, 255));
            btnExportExcel.setText("Xuất file Excel");
            btnExportExcel.setBorderRadius(5);
            btnExportExcel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

            btnReset.setBackground(new java.awt.Color(50, 145, 255));
            btnReset.setForeground(new java.awt.Color(255, 255, 255));
            btnReset.setText("Đặt lại");
            btnReset.setBorderRadius(5);
            btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headerCustom, javax.swing.GroupLayout.DEFAULT_SIZE, 1202, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(329, 329, 329)
                                                    .addComponent(rangeDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(30, 30, 30)
                                                    .addComponent(txtDateForm, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lblTo)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(37, 37, 37)
                                                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(65, 65, 65)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                    .addComponent(btnExportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGap(42, 42, 42)
                                                                    .addComponent(btnExportPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(tbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addComponent(headerCustom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(54, 54, 54)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(txtDateForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblTo)
                                                            .addComponent(txtDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rangeDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tbl, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnExportPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnExportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 40, Short.MAX_VALUE))
            );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private iuh.fit.se.group1.ui.component.custom.Button btnExportExcel;
        private iuh.fit.se.group1.ui.component.custom.Button btnExportPDF;
        private iuh.fit.se.group1.ui.component.custom.Button btnReset;
        private iuh.fit.se.group1.ui.component.custom.Button btnView;
        private iuh.fit.se.group1.ui.component.HeaderCustom headerCustom;
        private javax.swing.JLabel lblTo;
        private iuh.fit.se.group1.ui.component.chart.RangeDateButton rangeDateButton;
        private iuh.fit.se.group1.ui.component.table.Table tbl;
        private iuh.fit.se.group1.ui.component.custom.TextField txtDateForm;
        private iuh.fit.se.group1.ui.component.custom.TextField txtDateTo;
        // End of variables declaration//GEN-END:variables
}
