/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt 
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java 
 */
package iuh.fit.se.group1.ui.layout;

import iuh.fit.se.group1.entity.Surcharge;
import iuh.fit.se.group1.service.ImportExcelService;
import iuh.fit.se.group1.service.SurchargeService;
import iuh.fit.se.group1.ui.component.custom.message.Message;
import iuh.fit.se.group1.ui.component.modal.SurchageModal;
import iuh.fit.se.group1.ui.component.table.TableActionEvent;
import iuh.fit.se.group1.util.Constants;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import raven.glasspanepopup.GlassPanePopup;
import iuh.fit.se.group1.service.ExportExcelService;

/**
 *
 * @author Windows
 */
public class SurchargeManagement extends javax.swing.JPanel {

    /**
     * Creates new form SurchageManagement
     */
    private static final Logger log = LoggerFactory.getLogger(SurchargeManagement.class);
    private final SurchargeService surchargeService;

    public SurchargeManagement() {
        initComponents();
        custom();
        surchargeService = new SurchargeService(); 
        loadTable(surchargeService.getAllSurcharges());
    }

    private void loadTable(List<Surcharge> allSurcharges) {
        DefaultTableModel model = (DefaultTableModel) tblSurchage.getTbl().getModel();
        model.setRowCount(0);
        for (Surcharge surcharge : allSurcharges) {
            model.addRow(new Object[]{surcharge.getSurchargeId(), surcharge.getName(), Constants.VND_FORMAT.format(surcharge.getPrice())});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerCustom1 = new iuh.fit.se.group1.ui.component.HeaderCustom();
        tblSurchage = new iuh.fit.se.group1.ui.component.table.Table();
        jLabel1 = new javax.swing.JLabel();
        btnAddSurchage = new iuh.fit.se.group1.ui.component.custom.Button();
        btnExport = new iuh.fit.se.group1.ui.component.custom.Button();
        btnImport = new iuh.fit.se.group1.ui.component.custom.Button();

        setBackground(new java.awt.Color(241, 241, 241));

        tblSurchage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setBackground(new java.awt.Color(241, 242, 241));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Quản lý phụ phí");

        btnAddSurchage.setText("Thêm phụ phí");
        btnAddSurchage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddSurchage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSurchageActionPerformed(evt);
            }
        });

        btnExport.setText("Xuất Excel");
        btnExport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnImport.setText("Nhập excel");
        btnImport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tblSurchage, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddSurchage, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddSurchage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(tblSurchage, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSurchageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSurchageActionPerformed
        SurchageModal modal = new SurchageModal();
        modal.closeModel(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                GlassPanePopup.closePopupLast();
            }

        });
        modal.saveData(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                saveData(modal);
            }

            private void saveData(SurchageModal modal) {
                Valid result = getValid(modal);
                if (result.valid()) {
                    Surcharge surchargeSave = surchargeService.createSurcharge(new Surcharge(result.name(), result.price()));
                    if (surchargeSave == null) {
                        Message.showMessage("Lỗi", "Phụ phí với tên '" + result.name() + "' đã tồn tại!");
                        return;
                    }
                    DefaultTableModel model = (DefaultTableModel) tblSurchage.getTbl().getModel();
                    model.addRow(new Object[]{surchargeSave.getSurchargeId(), surchargeSave.getName(), Constants.VND_FORMAT.format(surchargeSave.getPrice())});
                    GlassPanePopup.closePopupLast();
                }
            }
        });
        GlassPanePopup.showPopup(modal);
    }//GEN-LAST:event_btnAddSurchageActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.Button btnAddSurchage;
    private iuh.fit.se.group1.ui.component.custom.Button btnExport;
    private iuh.fit.se.group1.ui.component.custom.Button btnImport;
    private iuh.fit.se.group1.ui.component.HeaderCustom headerCustom1;
    private javax.swing.JLabel jLabel1;
    private iuh.fit.se.group1.ui.component.table.Table tblSurchage;
    // End of variables declaration//GEN-END:variables

    private void custom() {

        headerCustom1.getLblTitle().setText(
                "<html><span style='color:white;'>Quản lý phụ phí</span>");
        headerCustom1.getLblTitle().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));

        btnAddSurchage.setBackground(new Color(108, 165, 200));
        btnAddSurchage.setForeground(Color.WHITE);
        btnAddSurchage.setBorderRadius(10);

        btnExport.setBackground(new Color(13, 200, 7));
        btnExport.setForeground(Color.WHITE);
        btnExport.setBorderRadius(10);

        btnImport.setBackground(new Color(255, 108, 3));
        btnImport.setForeground(Color.WHITE);
        btnImport.setBorderRadius(10);
        btnImport.addActionListener(ev -> {
            JFileChooser fileChooser = new JFileChooser();
            int result = fileChooser.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                ImportExcelService importService = new ImportExcelService();
                List<Surcharge> imported = importService.importSurchargesFromExcel(file);
                if (imported != null && !imported.isEmpty()) {
                    surchargeService.getAllSurcharges().addAll(imported);
                    loadTable(surchargeService.getAllSurcharges());
                    Message.showMessage("Thành công", "Đã import " + imported.size() + " phụ phí!");
                } else {
                    Message.showMessage("Lỗi", "Không có dữ liệu nào được import!");
                }
            }
        });
        btnAddSurchage.setIcon(FontIcon.of(FontAwesomeSolid.PLUS, 17, Color.WHITE), SwingConstants.RIGHT);
        btnImport.setIcon(FontIcon.of(FontAwesomeSolid.FILE_IMPORT, 17, Color.WHITE), SwingConstants.RIGHT);
        btnExport.setIcon(FontIcon.of(FontAwesomeSolid.FILE_EXPORT, 17, Color.WHITE), SwingConstants.RIGHT);

        String cols[] = {"Mã phụ phí", "Tên phụ phí", "Giá phụ phí", "Chức năng"};
        DefaultTableModel model = new DefaultTableModel(cols, 0);
        tblSurchage.getTbl().setModel(model);
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                DefaultTableModel model = (DefaultTableModel) tblSurchage.getTbl().getModel();
                String name = (String) model.getValueAt(row, 1);
                String price = String.valueOf(model.getValueAt(row, 2));

                SurchageModal modal = new SurchageModal();
                modal.getLblTitle().setText("Cập nhật phụ phí");
                modal.getBtnSave().setText("Cập nhật");

                modal.getTxtName().setText(name);
                modal.getTxtPrice().setText(price);

                modal.closeModel(ae -> GlassPanePopup.closePopupLast());
                modal.saveData(ae -> {
                    String title = "Xác nhận cập nhật phụ phí";
                    String message = "Bạn có chắc chắn muốn cập nhật phụ phí này không?";
                    Message.showConfirm(title, message, () -> {
                        var result = getValid(modal);
                        if (!result.valid) {
                            return;
                        }
                        Object idValue = model.getValueAt(row, 0);
                        System.out.println(">>> ID type: " + idValue.getClass() + " | value = " + idValue);
                        Surcharge entitySave = surchargeService.updateSurcharge(new Surcharge((Long) model.getValueAt(row, 0), result.name, result.price));

                        model.setValueAt(entitySave.getName(), row, 1);
                        model.setValueAt(Constants.VND_FORMAT.format(entitySave.getPrice()), row, 2);

                        GlassPanePopup.closePopupLast();
                    });
                });

                GlassPanePopup.showPopup(modal);
            }

            @Override
            public void onDelete(int row) {
                String title = "Xác nhận xóa phụ phí";
                String message = "Bạn có chắc chắn muốn xóa phụ phí này không?";
                Message.showConfirm(title, message, () -> {
                    JTable table = tblSurchage.getTbl();

                    if (table.isEditing()) {
                        table.getCellEditor().stopCellEditing();
                    }

                    DefaultTableModel model = (DefaultTableModel) table.getModel();
                    int rowDelete = table.getSelectedRow();

                    if (rowDelete >= 0) {
                        Long id = (Long) model.getValueAt(rowDelete, 0);

                        model.removeRow(rowDelete);

                        surchargeService.deleteSurcharge(id);
                    }
                });

            }

        };
        tblSurchage.setTableActionColumn(tblSurchage.getTbl(), 3, event, false);
        tblSurchage.getTbl().getColumnModel().getColumn(0).setPreferredWidth(200);
        tblSurchage.getTbl().getColumnModel().getColumn(1).setPreferredWidth(300);
        tblSurchage.getTbl().getColumnModel().getColumn(2).setPreferredWidth(200);
        tblSurchage.getTbl().getColumnModel().getColumn(3).setPreferredWidth(80);

        tblSurchage.getTbl().addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseMoved(java.awt.event.MouseEvent e) {
                int col = tblSurchage.getTbl().columnAtPoint(e.getPoint());
                if (col == 3) {
                    tblSurchage.getTbl().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                } else {
                    tblSurchage.getTbl().setCursor(Cursor.getDefaultCursor());
                }
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                tblSurchage.getTbl().clearSelection();
            }
        });
    }

    private record Valid(String name, boolean valid, BigDecimal price) {

    }

    private static Valid getValid(SurchageModal modal) {
        String name = modal.getTxtName().getText().trim();
        String price = modal.getTxtPrice().getText().trim();

        modal.getLblErrolSurchage().setText("");
        modal.getLblErrolPrice().setText("");

        Color red = Color.RED;
        modal.getLblErrolSurchage().setForeground(red);
        modal.getLblErrolPrice().setForeground(red);

        boolean valid = true;

        if (name.isEmpty()) {
            modal.getLblErrolSurchage().setText("Tên không được để trống!");
            valid = false;
        } else if (name.length() < 2) {
            modal.getLblErrolSurchage().setText("Tên quá ngắn (tối thiểu 2 ký tự)!");
            valid = false;
        }

        BigDecimal priceI = BigDecimal.ZERO;
        if (price.isEmpty()) {
            modal.getLblErrolPrice().setText("Giá không được để trống!");
            valid = false;
        } else {
            try {
                priceI = new BigDecimal(
                         price.replaceAll("[^\\d.-]", "").trim()
                );
                if (priceI.compareTo(BigDecimal.ZERO) <= 0) {
                    modal.getLblErrolPrice().setText("Giá phải lớn hơn 0!");
                    valid = false;
                }
            } catch (Exception e) {
                modal.getLblErrolPrice().setText("Giá phải là số hợp lệ!");
                valid = false;
                log.error("Lỗi chuyển đổi giá dịch vụ: ", e);
            }
        }
        return new Valid(name, valid, priceI);
    }

}
