/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.shift;

import iuh.fit.se.group1.ui.component.custom.AvatarLabel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.border.LineBorder;
import org.kordamp.ikonli.material.Material;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author Administrator
 */
public class ShiftCard extends javax.swing.JPanel {

    /**
     * Creates new form ShiftPanel
     */
    public ShiftCard() {
        initComponents();
        styleButton();
        styleCard();
    }
    private void styleCard() {
        // Làm trong suốt để tự vẽ nền
        setOpaque(false);
    }
     @Override
    protected void paintComponent(java.awt.Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int w = getWidth();
        int h = getHeight();
        int arc = 25;
        int shadow = 6;
        int headerHeight = 40;

        // 🎨 Bóng mờ phía sau
        for (int i = shadow; i > 0; i--) {
            float alpha = 0.05f * (shadow - i + 1);
            g2.setColor(new Color(0, 0, 0, (int) (alpha * 255)));
            g2.fillRoundRect(i, i, w - i * 2, h - i * 2, arc, arc);
        }

        // 🎨 Nền trắng
        g2.setColor(Color.WHITE);
        g2.fillRoundRect(0, 0, w - shadow, h - shadow, arc, arc);

        // 🎨 Header xanh bo 2 góc trên
        g2.setColor(new Color(51, 204, 255));
        g2.fillRoundRect(0, 0, w - shadow, headerHeight, arc, arc);
        g2.fillRect(0, headerHeight - arc, w - shadow, arc); // tránh bị lõm ở giữa

        g2.dispose();
        super.paintComponent(g);
    }

    private void styleButton() {
        // Tạo icon "+" bằng Ikonli (Material pack)
        FontIcon plusIcon = FontIcon.of(Material.ADD, 36, new Color(33, 150, 243));
        jButton1.setIcon(plusIcon);
        jButton1.setText(null); // ẩn text mặc định

        // Làm nút trong suốt, không border mặc định
        jButton1.setFocusPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);
        jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Gán kích thước nút
        jButton1.setSize(60, 60);

        // Hover: đổi màu icon
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plusIcon.setIconColor(new Color(25, 118, 210));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plusIcon.setIconColor(new Color(33, 150, 243));
            }
        });

        // ⚙️ Bo tròn nút bằng custom UI thay vì tạo nút mới
        jButton1.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
        @Override
        public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            int w = c.getWidth();
            int h = c.getHeight();
            int shadowSize = 3; // kích thước bóng

            // 🔹 Đổ bóng mềm
            for (int i = shadowSize; i > 0; i--) {
                float alpha = 0.06f * (shadowSize - i + 1);
                g2.setColor(new Color(0, 0, 0, (int) (alpha * 255)));
                g2.fillOval(i, i, w - i * 2, h - i * 2);
            }

            // 🔹 Nền tròn (hover sáng hơn)
            if (jButton1.getModel().isRollover()) {
                g2.setColor(new Color(245, 245, 245));
            } else {
                g2.setColor(Color.WHITE);
            }
            g2.fillOval(0, 0, w - shadowSize, h - shadowSize);

            // 🔹 Viền mảnh
            g2.setColor(new Color(230, 230, 230));
            g2.drawOval(0, 0, w - shadowSize - 1, h - shadowSize - 1);

            g2.dispose();
            super.paint(g, c); // Vẽ icon "+"
        }
    });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        avatarLabel1 = new iuh.fit.se.group1.ui.component.custom.AvatarLabel();
        jPanel2 = new javax.swing.JPanel();
        avatarLabel2 = new iuh.fit.se.group1.ui.component.custom.AvatarLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(450, 275));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("CA 02");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 61, 38));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("13H-18H");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 180, 50));

        jButton1.setPreferredSize(new java.awt.Dimension(60, 60));
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 70, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nguyễn Chí Tâm");

        jLabel4.setText("NV732221213");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatarLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(avatarLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 300, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Nguyễn Trần Phước Thịnh");

        jLabel6.setText("NV213812731");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatarLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(avatarLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 300, 70));
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        JFrame frame = new JFrame("Test ShiftCard");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(450, 275);
        frame.setLocationRelativeTo(null);

        ShiftCard card = new ShiftCard();
        frame.add(card);

        frame.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private iuh.fit.se.group1.ui.component.custom.AvatarLabel avatarLabel1;
    private iuh.fit.se.group1.ui.component.custom.AvatarLabel avatarLabel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
