/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.shift;

import iuh.fit.se.group1.ui.component.booking.InfoOrderPanel;
import iuh.fit.se.group1.ui.component.raven.panel.PanelShadow;

import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Administrator
 */
public class ShiftList extends JPanel {

    /**
     * Creates new form ShiftList
     */
    public ShiftList() {
        initComponents();
        setPreferredSize(new Dimension(290, getPreferredSize().height));
        addEmployees("Chó Thịnh đẹp trai", "CHOTHINH123", "/images/avttest.jpg");
        addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");
        addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");
        addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");
        addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");
        addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");
        addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");
        addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");addEmployees("Tâm cute", "NV002", "/images/avttest.jpg");
        
    }

    @Override
    protected void paintComponent(Graphics g) {
    super.paintComponent(g); // ✅ Gọi đầu tiên để xóa nền mặc định

    Graphics2D g2 = (Graphics2D) g.create();
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

    int w = getWidth();
    int h = getHeight();
    int arc = 5;
    int shadow = 6;

    // 🎨 Bóng mờ phía sau
    for (int i = shadow; i > 0; i--) {
        float alpha = 0.05f * (shadow - i + 1);
        g2.setColor(new Color(0, 0, 0, (int) (alpha * 255)));
        g2.fillRoundRect(i, i, w - i * 2, h - i * 2, arc, arc);
    }

    // 🎨 Nền trắng
    g2.setColor(Color.WHITE);
    g2.fillRoundRect(0, 0, w - shadow, h - shadow, arc, arc);

    g2.dispose();
}
public List<ShiftProfile> getSelectedEmployees() {
        List<ShiftProfile> selectedList = new ArrayList<>();
        
        for (Component c : pnlEmployees.getComponents()) {
            if (c instanceof ShiftProfile) {
                ShiftProfile profile = (ShiftProfile) c;
                if (profile.isSelected()) {
                    selectedList.add(profile);
                }
            }
        }
        
        return selectedList;
    }

    // ✅ Method để bỏ chọn tất cả radio button
    public void clearAllSelections() {
        for (Component c : pnlEmployees.getComponents()) {
            if (c instanceof ShiftProfile) {
                ShiftProfile profile = (ShiftProfile) c;
                profile.getjRadioButton2().setSelected(false);
                profile.setIsSelect(false);
                profile.updateBackground();
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollPaneWin111 = new iuh.fit.se.group1.ui.component.scroll.ScrollPaneWin11();
        pnlEmployees = new javax.swing.JPanel();

        setBackground(new java.awt.Color(241, 241, 241));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách nhân viên");

        pnlEmployees.setLayout(new javax.swing.BoxLayout(pnlEmployees, javax.swing.BoxLayout.Y_AXIS));
        scrollPaneWin111.setViewportView(pnlEmployees);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void addEmployees(String employeeName, String code, String imagePath) {
        ShiftProfile shiftProfile = new ShiftProfile();
        shiftProfile.getLblName().setText(employeeName);
        shiftProfile.getLblCode().setText(code);
        // todo:
         try {
        // Nếu ảnh nằm trong thư mục resources (ví dụ: /images/avttest.jpg)
            URL url = getClass().getResource(imagePath);
            if (url != null) {
                ImageIcon icon = new ImageIcon(url);
                Image avatar = icon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                shiftProfile.getAvatarLabel().setImage(avatar); // ✅ Gán ảnh vào AvatarLabel
                System.out.println("✅ Ảnh avatar URL: " + url);
            } else {
                System.err.println("❌ Không tìm thấy ảnh: " + imagePath);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        pnlEmployees.add(shiftProfile);
        JSeparator line = new JSeparator(SwingConstants.HORIZONTAL);
        line.setMaximumSize(new Dimension(Integer.MAX_VALUE, 1)); // độ cao 1px, full width
        pnlEmployees.add(line);
        int profileHeight = 80;
        int lineHeight = 1;

        // Đếm số lượng phần tử trong panel
        int componentCount = pnlEmployees.getComponentCount();

        // Tính tổng chiều cao: mỗi 2 component là 1 profile + 1 line
        int pairCount = componentCount / 2; 
        int contentHeight = pairCount * (profileHeight + lineHeight);

        // Nếu cuối cùng không có line (thêm nhân viên cuối), có thể +80
        if (componentCount % 2 != 0) {
            contentHeight += profileHeight;
        }

        // Cập nhật kích thước panel
        pnlEmployees.setPreferredSize(new Dimension(pnlEmployees.getWidth(), contentHeight));
        scrollPaneWin111.setViewportView(pnlEmployees);
        pnlEmployees.revalidate();
        pnlEmployees.repaint();
        shiftProfile.addMouseListener(shiftProfile);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlEmployees;
    private iuh.fit.se.group1.ui.component.scroll.ScrollPaneWin11 scrollPaneWin111;
    // End of variables declaration//GEN-END:variables
}
