/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package iuh.fit.se.group1.ui.component.booking;

import com.raven.datechooser.DateChooser;
import iuh.fit.se.group1.ui.component.custom.Combobox;
import iuh.fit.se.group1.ui.component.custom.TextField;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.lang.reflect.Field;

/**
 *
 * @author THIS PC
 */
public class InfoCustomerPanel extends javax.swing.JPanel {
    
    private int borderRadius = 8;

    private DateChooser dateChooser;

    /**
     * Creates new form InfoCustomerPanel
     */
    public InfoCustomerPanel() {
        initComponents();
        setOpaque(false);
        lblTitle.setIcon(FontIcon.of(FontAwesomeSolid.USER, 20, lblTitle.getForeground()));
        dateChooser = new DateChooser();
        dateChooser.toDay();
        dateChooser.setTextRefernce(txtDob);
        cboGender.addItem("Nam");
        cboGender.addItem("Nữ");
        cboGender.setBackground(new java.awt.Color(240, 248, 255));
        cboGender.setForeground(new java.awt.Color(51, 51, 51));
        cboGender.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));

    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int offset = 2;            // độ lệch bóng
        Color shadowColor = new Color(0, 0, 0, 10); // màu bóng (đen mờ)

        int width = getWidth();
        int height = getHeight();

        // Vẽ bóng (vẽ sau, lệch nhẹ xuống phải)
        g2.setColor(shadowColor);
        g2.fillRoundRect(offset, offset, width - 1, height - 1, borderRadius, borderRadius);

        // Vẽ nền panel thật (che bóng phía trên)
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, width - offset - 1, height - offset - 1, borderRadius, borderRadius);

        g2.dispose();
        super.paintComponent(g);
    }

    public void addActionTxtCitizenId(ActionListener actionListener) {
        txtCitizen.addActionListener(actionListener);
    }

    public Combobox getCboGender() {
        return cboGender;
    }

    public void setCboGender(Combobox cboGender) {
        this.cboGender = cboGender;
    }

    public TextField getTxtCustomerName() {
        return txtCustomerName;
    }

    public void setTxtCustomerName(TextField txtTCustomerName) {
        this.txtCustomerName = txtTCustomerName;
    }

    public TextField getTxtPhoneNumber() {
        return txtPhoneNumber;
    }

    public void setTxtPhoneNumber(TextField txtPhoneNumber) {
        this.txtPhoneNumber = txtPhoneNumber;
    }

    public TextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(TextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public TextField getTxtDob() {
        return txtDob;
    }

    public void setTxtDob(TextField txtDob) {
        this.txtDob = txtDob;
    }

    public TextField getTxtCitizen() {
        return txtCitizen;
    }

    public void setTxtCitizen(TextField txtCitizen) {
        this.txtCitizen = txtCitizen;
    }

    public JSeparator getSpn() {
        return spn;
    }

    public void setSpn(JSeparator spn) {
        this.spn = spn;
    }

    public DateChooser getDateChooser() {
        return dateChooser;
    }

    public void setDateChooser(DateChooser dateChooser) {
        this.dateChooser = dateChooser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        spn = new javax.swing.JSeparator();
        lblCitizen = new javax.swing.JLabel();
        txtCitizen = new iuh.fit.se.group1.ui.component.custom.TextField();
        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new iuh.fit.se.group1.ui.component.custom.TextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new iuh.fit.se.group1.ui.component.custom.TextField();
        lblDob = new javax.swing.JLabel();
        txtDob = new iuh.fit.se.group1.ui.component.custom.TextField();
        lblGender = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new iuh.fit.se.group1.ui.component.custom.TextField();
        cboGender = new iuh.fit.se.group1.ui.component.custom.Combobox();
        cbDeposit = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(131, 176, 211));
        lblTitle.setText("Khách hàng");
        lblTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        spn.setBackground(new java.awt.Color(255, 255, 51));
        spn.setForeground(new java.awt.Color(217, 217, 217));
        spn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));

        lblCitizen.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblCitizen.setText("CCCD:");

        txtCitizen.setBorderColor(new java.awt.Color(105, 105, 105));
        txtCitizen.setBorderRadius(3);

        lblCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblCustomerName.setText("Tên khách hàng:");

        txtCustomerName.setBorderColor(new java.awt.Color(105, 105, 105));
        txtCustomerName.setBorderRadius(3);

        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblPhoneNumber.setText("Số điện thoại:");

        txtPhoneNumber.setBorderColor(new java.awt.Color(105, 105, 105));
        txtPhoneNumber.setBorderRadius(3);
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        lblDob.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblDob.setText("Ngày sinh:");

        txtDob.setBorderColor(new java.awt.Color(105, 105, 105));
        txtDob.setBorderRadius(3);

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblGender.setText("Giới tính:");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblEmail.setText("Email: ");

        txtEmail.setBorderColor(new java.awt.Color(105, 105, 105));
        txtEmail.setBorderRadius(3);

        cbDeposit.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        cbDeposit.setText("Tiền cọc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spn, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(cbDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhoneNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDob)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCitizen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDob, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbDeposit)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbDeposit;
    private iuh.fit.se.group1.ui.component.custom.Combobox cboGender;
    private javax.swing.JLabel lblCitizen;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSeparator spn;
    private iuh.fit.se.group1.ui.component.custom.TextField txtCitizen;
    private iuh.fit.se.group1.ui.component.custom.TextField txtCustomerName;
    private iuh.fit.se.group1.ui.component.custom.TextField txtDob;
    private iuh.fit.se.group1.ui.component.custom.TextField txtEmail;
    private iuh.fit.se.group1.ui.component.custom.TextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
